- name: DnsMasq
  become: true
  block:
  - name: Stop and disable systemd-resolved
    service:
      name: systemd-resolved
      state: stopped
      enabled: false

  - name: "Install base  dnsmasq"
    apt:
      name:
        - dnsmasq
      state: present

  - name: Template resolv.conf
    template:
      force: yes
      src: resolv.j2
      dest: "/etc/resolv.conf"

  - name: Template dnsmasq.conf
    template:
      force: yes
      src: dnsmasq.j2
      dest: "/etc/dnsmasq.conf"

  - name: Template NetworkManager.conf
    template:
      force: yes
      src: NetworkManager.j2
      dest: "/etc/NetworkManager/NetworkManager.conf"


  - name: restart dnsmasq service
    changed_when: false
    service:
      name: dnsmasq
      state: restarted