- name: Consul update
  become: true
  when: update_consul|bool == true
  block:
    - name: stop consul service
      failed_when: false
      service:
        name: consul
        state: stopped
        enabled: false

    - name : Check consul installation present
      stat:
        path: /usr/local/bin/consul
      register: consulInstalled

    - name: Consul update
      become: true
      when: consulInstalled.stat.exists
      block:

        - name: Download consul binary
          get_url:
            url: https://releases.hashicorp.com/consul/{{consul_version}}/consul_{{consul_version}}_linux_amd64.zip
            dest: /tmp/consul{{consul_version}}_linux_amd64.zip
            owner: "{{ consul_user }}"
            group: "{{ consul_group }}"
            mode: 0755
            checksum: "{{consul_checksum}}"
          register: consul_download

        - name: "Unzip consul archive"
          unarchive:
            src: "{{ consul_download.dest }}"
            dest: /usr/local/bin
            copy: no
            owner: "{{ consul_user }}"
            group: "{{ consul_group }}"
            mode: 0755

        - name: Install consul autocomplete for root
          shell: |
            consul -autocomplete-install
          register: install
          changed_when: false
          # a reinstall triggers an error. Ignore this
          failed_when: install.rc > 2

        - name: Install consul autocomplete for user
          become: false
          shell: |
            consul -autocomplete-install
          changed_when: false
          register: install
          # a reinstall triggers an error. Ignore this
          failed_when: install.rc > 2

    - name: start consul service
      service:
        name: consul
        state: started
        enabled: true