- name: Consul uninstall
  become: true
  when: uninstall_consul|bool == true
  block:
    - name: stop consul service
      failed_when: false
      service:
        name: consul
        state: stopped
        enabled: false

    - name: "Delete consul dir if needed"
      ansible.builtin.file:
        path: "{{consul_data_dir}}"
        owner: vault
        state: absent
        mode: '0755'

    - name: "Delete consul home dir if needed"
      ansible.builtin.file:
        path: "{{consul_home_dir}}"
        owner: vault
        state: absent
        mode: '0755'

    - name: "Delete Consul installation"
      ansible.builtin.file:
        path: /usr/local/bin/consul
        owner: vault
        state: absent
        mode: '0755'


- name : Check consul installation present
  stat:
    path: /usr/local/bin/consul
  register: consulInstalled


- name: Create consul home dir
  become: true
  file:
    path: "{{consul_home_dir }}"
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    state: directory
    mode: '0755'

- name: Create consul data dir
  become: true
  file:
    path: "{{ consul_data_dir }}"
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    state: directory
    mode: '0755'

- name: Consul install
  become: true
  when: not consulInstalled.stat.exists
  block:
    - name: "Create consul dir if needed"
      become: true
      ansible.builtin.file:
        path: "{{consul_data_dir}}"
        owner: consul
        group: consul
        state: directory
        mode: '0755'

    - name: Download consul binary
      get_url:
        url: https://releases.hashicorp.com/consul/{{consul_version}}/consul_{{consul_version}}_linux_amd64.zip
        dest: /tmp/consul{{consul_version}}_linux_amd64.zip
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0755
        checksum: "{{consul_checksum}}"
      register: consul_download

    - name: "Unzip consul archive"
      unarchive:
        src: "{{ consul_download.dest }}"
        dest: /usr/local/bin
        copy: no
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0755

    - name: Install consul autocomplete for root
      shell: |
        consul -autocomplete-install
      register: install
      changed_when: false
      # a reinstall triggers an error. Ignore this
      failed_when: install.rc > 2

    - name: Install consul autocomplete for user
      become: false
      shell: |
        consul -autocomplete-install
      changed_when: false
      register: install
      # a reinstall triggers an error. Ignore this
      failed_when: install.rc > 2

- name: Consul config files
  become: true
  block:
    - name: config file server
      when: is_master_host
      template:
        force: yes # replace the remote file when contents are different than the source.
        src: consulhcl/consul_master.j2
        dest: "{{consul_home_dir}}/consul.hcl"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"

    - name: config file worker
      when: is_worker_host
      template:
        force: yes # replace the remote file when contents are different than the source.
        src: consulhcl/consul_worker.j2
        dest: "{{consul_home_dir}}/consul.hcl"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
  vars:
    consul_encrypt_key: "G1CHAD7wwu0tU28BlKkirSahTJ/Tqpo9ClOAycQAUwE="