- name: Consul uninstall
  become: true
  when: uninstall_consul|bool == true
  block:
    - name: stop consul service
      failed_when: false
      service:
        name: consul
        state: stopped
        enabled: false


    - name: "Delete secint dir {{secint_build_dir}} if present"
      ansible.builtin.file:
        path: "{{ secint_build_dir}}"
        state: absent

    - name: "Delete consul dir  {{consul_data_dir}} if present"
      ansible.builtin.file:
        path: "{{consul_data_dir}}"
        state: absent

    - name: "Delete consul dir  {{consul_client_jwt_dir}} if present"
      ansible.builtin.file:
        path: "{{consul_client_jwt_dir}}"
        state: absent

    - name: "Delete consul conf dir  {{consul_conf_dir}} if present"
      ansible.builtin.file:
        path: "{{consul_conf_dir}}"
        state: absent

    - name: "Delete consul cert dir  {{consul_cert_path}} if present"
      ansible.builtin.file:
        path: "{{consul_cert_path}}"
        state: absent

    - name: "Delete Consul installation"
      ansible.builtin.file:
        path: /usr/local/bin/consul
        state: absent
        mode: '0755'


- name : Check consul installation present
  stat:
    path: /usr/local/bin/consul
  register: consulInstalled


- name: Create consul home dir
  become: true
  file:
    path: "{{consul_conf_dir}}"
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    state: directory
    mode: '0755'

- name: Create consul data dir
  become: true
  file:
    path: "{{ consul_data_dir }}"
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    state: directory
    mode: '0755'


- name: Consul install certs
  become: true
  when: not consulInstalled.stat.exists  or update_certificates|bool == true
  block:
    - name: install_cert handler consul
      include_tasks: handlers/generate_consul_certs.yml

- name: Consul install
  become: true
  when: not consulInstalled.stat.exists
  block:


    - name: "Create consul dir if needed"
      become: true
      ansible.builtin.file:
        path: "{{consul_data_dir}}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        state: directory
        mode: '0755'

    - name: Download consul binary
      get_url:
        url: https://releases.hashicorp.com/consul/{{consul_version}}/consul_{{consul_version}}_linux_amd64.zip
        dest: /tmp/consul{{consul_version}}_linux_amd64.zip
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0755
        checksum: "{{consul_checksum}}"
      register: consul_download

    - name: "Unzip consul archive"
      unarchive:
        src: "{{ consul_download.dest }}"
        dest: /usr/local/bin
        copy: no
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0755

    - name: Install consul autocomplete for root
      shell: |
        consul -autocomplete-install
      register: install
      changed_when: false
      # a reinstall triggers an error. Ignore this
      failed_when: install.rc > 2

    - name: Install consul autocomplete for user
      become: false
      shell: |
        consul -autocomplete-install
      changed_when: false
      register: install
      # a reinstall triggers an error. Ignore this
      failed_when: install.rc > 2

