# The certificates are installed only on servers
# auto_encrypt setting ensures that the client certificate generations is automated by consul
- name: Certificates
  block:
    - name: "Update certificates {{ update_certificates|bool == true }} "
      become: true
      file:
        state: absent
        path: "{{consul_cert_path}}"
      when: update_certificates|bool == true

    - name : "Check if consul certificate exist on node -> {{consul_cert_path}}/consul.pem"
      stat:
        path: "{{consul_cert_path}}/consul.pem"
      register: cert

- name: Install certificates
  when: not cert.stat.exists
  block:

    - name: "Change file ownership, group and permissions for {{consul_cert_path}}"
      become: true
      ansible.builtin.file:
        path: "{{consul_cert_path}}"
        owner: "{{consul_user}}"
        group: "{{consul_group}}"
        state: directory
        mode: '0755'

    - name: "Create consul certificate work dir if needed"
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{local_cert_gen_path}}"
        state: directory

    - name: Template consul server .json
      when: is_master_host
      delegate_to: localhost
      template:
        force: yes
        src: cert/consul_server.j2
        dest: "{{local_cert_gen_path}}/consul.json"

    - name: Template consul client .json
      when: is_worker_host
      delegate_to: localhost
      template:
        force: yes
        src: cert/consul_client.j2
        dest: "{{local_cert_gen_path}}/consul.json"


    - name: "Generate consul certificates in {{local_cert_gen_path}}"
      when: is_master_host
      delegate_to: localhost
      shell: |
        cfssl gencert \
          -ca ../cloudlocal/cluster-ca/cluster-ca.pem \
          -ca-key ../cloudlocal/cluster-ca/cluster-ca-key.pem \
          -config {{local_ca_cert_conf}} \
          -profile peer consul.json | cfssljson -bare consul
      args:
        chdir: "{{local_cert_gen_path}}"

    - name: "Generate consul certificates in {{local_cert_gen_path}}"
      when: is_worker_host
      delegate_to: localhost
      shell: |
        cfssl gencert \
          -ca ../cloudlocal/cluster-ca/cluster-ca.pem \
          -ca-key ../cloudlocal/cluster-ca/cluster-ca-key.pem \
          -config {{local_ca_cert_conf}} \
          -profile client consul.json | cfssljson -bare consul
      args:
        chdir: "{{local_cert_gen_path}}"

    - name: "Generate consul certificates in {{local_cert_gen_path}}"
      when: is_worker_host
      delegate_to: localhost
      shell: |
        cfssl gencert \
          -ca ../cloudlocal/cluster-ca/cluster-ca.pem \
          -ca-key ../cloudlocal/cluster-ca/cluster-ca-key.pem \
          -config {{local_ca_cert_conf}} \
          -profile peer consul.json | cfssljson -bare consul
      args:
        chdir: "{{local_cert_gen_path}}"

    - name: "Copy certificate to {{consul_cert}}"
      become: true
      ansible.builtin.copy:
        src: "{{local_cert_gen_path}}/consul.pem"
        dest: "{{consul_cert}}"
        owner: "{{consul_user}}"
        group: "{{consul_group}}"
        mode: '0644'

    - name: "Copy certificate key to {{consul_cert_key}}"
      become: true
      ansible.builtin.copy:
        src: "{{local_cert_gen_path}}/consul-key.pem"
        dest: "{{consul_cert_key}}"
        owner: "{{consul_user}}"
        group: "{{consul_group}}"
        mode: '0644'

    - name: restart consul service
      ignore_errors: true
      become: true
      service:
        name: consul
        state: restarted


