#https://learn.hashicorp.com/tutorials/consul/deployment-guide
- name: Consul installation
  block:
  - name: "Create consul user"
    import_tasks: user.yml

  - name: Copy certificates from master 0
    import_tasks: copy_certs_from_master_0.yml

  - name: "Copy certificates from master 0"
    import_tasks: install_certificates.yml
    when: is_master_host

  - name: "Install consul"
    import_tasks: consul_install.yml

  - name: "Install consul-template"
    import_tasks: consul_template_install.yml



  vars:
    consul_data_dir: "/opt/deployments/core/consul/data"
    consul_conf_dir: "/etc/consul.d"
    consul_data_center: "nomadder_1"
    consul_cert_path: "/etc/opt/certs/consul"
    consul_sever_cert: "{{consul_cert_path}}/consul-server.pem"
    consul_sever_cert_key: "{{consul_cert_path}}consul-server-key.pem"
    consul_dns: "consul.{{tls_san}}"
    consul_servers:
      - "127.0.0.1"
      - "localhost"
      - "{{consul_dns}}"
      - "server.{{consul_data_center}}.consul"
      - "server.{{host_name}}.{{consul_data_center}}.consul"
