#https://learn.hashicorp.com/tutorials/consul/deployment-guide
- name: Consul installation
  block:

  - name: "Create consul user"
    import_tasks: user.yml

  - name: "Install consul"
    import_tasks: consul_install.yml

  vars:
    consul_data_dir: "/opt/deployments/core/consul/data"
    consul_home_dir: "/etc/consul.d"