#https://learn.hashicorp.com/tutorials/consul/deployment-guide
- name: Consul installation
  block:
  - name: "Create consul user"
    import_tasks: user.yml

  - name: "Install consul"
    import_tasks: consul_install.yml

#  - name: "Build and copy secint"
#    import_tasks: build_and_copy_secinit.yml
#    run_once: true
#    when: is_master_host

  # The jwt tokens are generated on the master
  # This task copies the jwt tokens from master to the consul client hosts
#  - name: "Copy secint jwt tokens"
#    import_tasks: copy_jwt.yml
#    when: is_worker_host

  - name: Consul config files
    import_tasks: copy_consul_config_files.yml


  - name: "Install consul-template"
    import_tasks: consul_template_install.yml

  - name: "Systemd service"
    import_tasks: consul_systemd_install.yml

  vars:
    consul_initial_management_token: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    consul_initial_agent_token: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    consul_encrypt_key: "G1CHAD7wwu0tU28BlKkirSahTJ/Tqpo9ClOAycQAUwE="
    secint_build_dir: "/etc/ssl/private/secint"
    consul_data_dir: "{{systemd_install_dir}}/consul/data"
    consul_client_jwt_dir: "{{consul_data_dir}}/tokens/jwt"
    consul_client_jwt_file: "{{consul_client_jwt_dir}}/{{host_name}}.jwt"
    consul_conf_dir: "/etc/consul.d"
    consul_cert_path: "/etc/opt/certs/consul"
    consul_cert: "{{consul_cert_path}}/consul.pem"
    consul_cert_key: "{{consul_cert_path}}/consul-key.pem"
