---
#- name: get service facts
#  service_facts:
#- debug:
#    var: ansible_facts.services['ufw.service']

- name: Vault installation
  block:
  - name: Set local cert path
    set_fact:
      #cert path on nodes
      vault_cert_copy_path: /etc/opt/certs
      vault_cert_path: /etc/opt/certs/vault
      # cert path on local host
      local_ca_cert_path: "{{role_path}}/../certificates_generate/files/certs/vault"
      cacheable: true

  - name: Set local cert files
    set_fact:

      vault_cert: "{{vault_cert_path}}/vault.pem"
      vault_cert_key: "{{vault_cert_path}}/vault-key.pem"
      ca_cert: "{{ca_cert_path}}/ca/ca.pem"
      cacheable: true

  - name: "Create vault user"
    import_tasks: user.yml

  - name: "Vault certificates"
    import_tasks: certificates.yml

  - name: "Vault installation"
    import_tasks: vault_install.yml

  tags:
    - vault
    - cert
    - cert_install

