---
#ansible_ssh_port: 22
# This fixes the warning Distribution centos  on host  should use /usr/libexec/platform-python, but is using /usr/bin/python
# But makes the assumption that all hosts have python 3 installed.
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_user: cloudmaster
ansible_ssh_timeout: 360
# https://mschuette.name/wp/2019/01/ansible-and-vagrant-ssh-keys/
#TODO generate
ansible_ssh_private_key_file: "{{ inventory_dir }}/../ssh/id_rsa"
env: "production"

# Somehow the assan dns not works. Services in grafana goes up and down.
publicdns:
  - "8.8.8.8"
  - "1.1.1.1"
