host_default_if : "eth1"
host_public_if : "eth0"
host_ip: "{{ ansible_facts['eth1']['ipv4']['address']}}"
host_ips:
  - "{{ ansible_facts['eth0']['ipv4']['address']}}"
  - "{{ ansible_facts['eth1']['ipv4']['address']}}"
