- name: Create postgres volume
  when: host_name == 'worker-01'
  block:

  - name: Create stack core postgres volumes
    include_tasks: nomad/tasks/nomad_volumes.yml
    loop:
      - { name: 'security_postgres_volume' , path: '{{postgres_volume}}'}



  vars:
    postgres_volume: "{{nomad_volumes_dir}}/core/postgres"

