- name: Create postgres volume
  when: host_name == 'worker-01'
  block:

  - name: Create stack core postgres volumes
    include_tasks: nomad/tasks/nomad_volumes.yml
    loop:
      - { name: 'stack_core_keycloak_postgres_volume' , path: '{{stack_core_keycloak_postgres_volume}}'}

  - name: restart nomad if needed
    become: true
    # fact comes from task nomad/tasks/nomad_volumes.yml
    when: volume_changed | bool == true
    service:
      name: nomad
      state: restarted
    register: nomadService
    until: nomadService.status.ActiveState == "active"
    async: 300
    retries: 10
    delay: 5

  vars:
    stack_core_keycloak_postgres_volume: "{{nomad_volumes_dir}}/core/postgres"

- name: Create Minio volume
  when: host_name == 'worker-01'
#  when: is_worker_host
  block:

    - name: Create stack core create minio volume
      include_tasks: nomad/tasks/nomad_volumes.yml
      loop:
        - { name: 'stack_core_minio_volume' , path: '{{stack_core_minio_volume}}'}

    - name: restart nomad if needed
      become: true
      # fact comes from task nomad/tasks/nomad_volumes.yml
      when: volume_changed | bool == true
      service:
        name: nomad
        state: restarted
      register: nomadService
      until: nomadService.status.ActiveState == "active"
      async: 300
      retries: 10
      delay: 5

  vars:
    stack_core_minio_volume: "{{nomad_volumes_dir}}/core/minio"