[localhost]
127.0.0.1

[master01]
172.21.1.11

[worker01]
172.21.1.21

; Due to limitations in prod env with no vpn access the build host is deprecated
; Cluster setup must be runnable from master_0 over ansible and stadck deployments needs a public docker registry
[build:children]
;master01

[masters:children]
master01

[workers:children]
worker01
;172.21.1.21
;172.21.1.22


[cluster:children]
masters
workers
