[localhost]
127.0.0.1

[master01]
172.21.1.11

[worker01]
172.21.1.21

[build:children]
master01

[masters:children]
master01

[workers:children]
worker01
;172.21.1.21
;172.21.1.22


[cluster:children]
masters
workers
