---
# At first install additional stuff that needed for localhost
- hosts: localhost
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
  name: "Setup local environment"
  gather_facts: no
  roles:
    - {role: localhost, tags: ['localhost']}


- hosts: all, !localhost
  name: "Enable shared folders {{enable_shared_folders}}"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
  gather_facts: yes
  roles:
    - {role: shared_folder, tags: ['shared_folder']}

# Install tools and update the nodes ( not related to nomad hashi stack )
- hosts: all, !localhost
  name: "Nodes base installations"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
  gather_facts: yes
  roles:
    - {role: common, tags: ['nodes']}