---
- hosts: localhost
  name: "Generate certificates for tls"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
    - vars/vault.yml
  gather_facts: no
  roles:
    - {role: certificates_generate, tags: ['cert','cert_gen']}

- hosts: all,!localhost
  name: "Master and worker base installations"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
    - vars/vault.yml
  gather_facts: yes
  roles:
    - {role: certificates_install, tags: ['cert','cert_install']}
    - {role: dnsmasq, tags: ['dnsmasq']}

# Single master setup
# HA Setup is planed in second release
- hosts: masters[0]
  name: "Master [0] installations"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
    - vars/vault.yml
  gather_facts: yes
  roles:
    - {role: master_vault, tags: ['cert','vault']}

- hosts: all,!localhost
  name: "Master and worker platform installations"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
    - vars/vault.yml
  gather_facts: yes
  roles:
    - {role: consul, tags: ['cert','consul']}
- hosts: all
  name: "Facts"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
    - vars/vault.yml
  gather_facts: yes

  tags:
    facts