---
- hosts: localhost
  name: "Generate certificates for tls"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
    - vars/vault.yml
  gather_facts: no
  roles:
    - {role: certificates_generate, tags: ['cert','cert_gen']}

- hosts: all,!localhost
  name: "Install certificates"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
    - vars/vault.yml
  gather_facts: no
  roles:
    - {role: certificates_install, tags: ['cert','cert_install']}

# Single master setup
# HA Setup is planed in second release
- hosts: masters[0]
  name: "Master [0] installations"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
    - vars/vault.yml
  gather_facts: yes
  roles:
    - {role: master_dnsmasq, tags: ['dns']}
    - {role: master_vault, tags: ['cert','cert_install','vault']}

- hosts: workers
  name: "Worker installations"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
    - vars/vault.yml
  gather_facts: yes
  roles:
    - {role: worker_dnsmasq, tags: ['dns']}
#- hosts: all
#  name: "Facts"
#  vars_files:
#    - vars/versions.yml
#    - vars/common_vars.yml
#    - vars/vault.yml
#  gather_facts: yes
#  tasks:
#    - debug:
#        var: ansible_facts
#  tags:
#    facts