---
# install vault only on first master
- hosts: masters[0]
  name: "Nodes base installations"
  vars_files:
    - vars/versions.yml
    - vars/common_vars.yml
  gather_facts: yes
  roles:
    - role: vault
  tags:
    - vault