{
 "title": "Nodes Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Os overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{job=\"integrations/node_exporter\",instance=~\"$node\"} * on(instance) group_left(pretty_name,name,version_codename,version_id) node_os_info{job=\"integrations/node_exporter\",instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Overview",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "up{job=\"integrations/node_exporter\",instance=~\"$node\"}[1m]",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1- max_over_time(up{job=\"integrations/node_exporter\",instance=~\"$node\"}[24h]) unless max_over_time(up{job=\"integrations/node_exporter\",instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Used $node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (1- irate(node_cpu_seconds_total{mode=\"idle\",instance=\"$node\"}[5m])) / sum by (instance) (irate(node_cpu_seconds_total{instance=\"$node\"}[5m])) * 100"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "RAM Used $node",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"integrations/node_exporter\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"integrations/node_exporter\"})"
    }
   ]
  },
  { "title": "File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Root FS Used $node",
   "type": "stat",
   "description": "Used Root FS",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"integrations/node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"integrations/node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  }
 ]
}