- name: Journald config
  become: true
  block:
    - name: Template Journald config
      template:
        force: yes
        src: service/journald.j2
        dest: /etc/systemd/journald.conf
      register: config

    - name: Reload systemd
      when: config.changed
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart journald service
      when: config.changed
      service:
        name: systemd-journald
        state: restarted
        enabled: yes
      register: journaldservice
      until: journaldservice.status.ActiveState == "active"
      retries: 10
      delay: 5