# The certificates are installed only on servers
# auto_encrypt setting ensures that the client certificate generations is automated by consul
- name: Certificates
  block:

    - name: "Update certificates {{ update_certificates|bool == true }} "
      become: true
      file:
        state: absent
        path: "{{nomad_cert_path}}"
      when: update_certificates|bool == true

    - name : "Check if consul certificate exist on node -> {{nomad_cert}}"
      stat:
        path: "{{nomad_cert}}"
      register: cert

- name: Install certificates
  when: not cert.stat.exists
  block:

    - name: "Create nomad certificate dir if needed {{nomad_cert_path}}"
      become: true
      ansible.builtin.file:
        path: "{{nomad_cert_path}}"
        owner: "{{nomad_user}}"
        group: "{{nomad_group}}"
        state: directory
        mode: '0755'

    - name: "Create nomad certificate work dir if needed"
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{local_cert_gen_path}}/cert"
        state: directory

    - name: Template nomad_server.json
      when: is_master_host
      delegate_to: localhost
      template:
        force: yes
        src: cert/nomad_server.j2
        dest: "{{local_cert_gen_path}}/nomad_server.json"

    - name: Template nomad_cli.json
      when: is_master_host
      delegate_to: localhost
      template:
        force: yes
        src: cert/nomad_cli.j2
        dest: "{{local_cert_gen_path}}/nomad_cli.json"

    - name: Template nomad_client.json
      when: is_worker_host
      delegate_to: localhost
      template:
        force: yes
        src: cert/nomad_client.j2
        dest: "{{local_cert_gen_path}}/nomad_client.json"

    - name: "Generate nomad server certificates in {{local_cert_gen_path}}"
      when: is_master_host
      delegate_to: localhost
      shell: |
        cfssl gencert \
          -ca ../../cloudlocal/cluster-ca/cluster-ca.pem \
          -ca-key ../../cloudlocal/cluster-ca/cluster-ca-key.pem \
          -config {{local_ca_cert_conf}} \
          -profile peer ../nomad_server.json | cfssljson -bare nomad
        
        cfssl gencert \
          -ca ../../cloudlocal/cluster-ca/cluster-ca.pem \
          -ca-key ../../cloudlocal/cluster-ca/cluster-ca-key.pem \
          -config {{local_ca_cert_conf}} \
          -profile client ../nomad_cli.json | cfssljson -bare nomad-cli
      args:
        chdir: "{{local_cert_gen_path}}/cert"

    - name: "Generate nomad client certificates in {{local_cert_gen_path}}"
      when: is_worker_host
      delegate_to: localhost
      shell: |
        cfssl gencert \
          -ca ../../cloudlocal/cluster-ca/cluster-ca.pem \
          -ca-key ../../cloudlocal/cluster-ca/cluster-ca-key.pem \
          -config {{local_ca_cert_conf}} \
          -profile peer ../nomad_client.json | cfssljson -bare nomad
      args:
        chdir: "{{local_cert_gen_path}}/cert"

    - name: "Copy servr certificate to {{nomad_cert_path}}"
      become: true
      when: is_master_host
      ansible.builtin.copy:
        src: "{{item}}"
        dest: "{{nomad_cert_path}}"
        owner: "{{nomad_user}}"
        group: "{{nomad_group}}"
        mode: '0644'
      with_items:
        - "{{local_cert_gen_path}}/cert/nomad.pem"
        - "{{local_cert_gen_path}}/cert/nomad-key.pem"
        - "{{local_cert_gen_path}}/cert/nomad-cli.pem"
        - "{{local_cert_gen_path}}/cert/nomad-cli-key.pem"

    - name: "Copy client certificates to {{nomad_cert_path}}"
      become: true
      when: is_worker_host
      block:
        - name: "Copy certificate to {{nomad_cert_path}}"
          ansible.builtin.copy:
            src: "{{item}}"
            dest: "{{nomad_cert_path}}"
            owner: "{{nomad_user}}"
            group: "{{nomad_group}}"
            mode: '0644'
          with_items:
            - "{{local_cert_gen_path}}/cert/nomad.pem"
            - "{{local_cert_gen_path}}/cert/nomad-key.pem"


    - name: restart nomad service
      ignore_errors: true
      become: true
      service:
        name: nomad
        state: restarted


