# see https://learn.hashicorp.com/tutorials/nomad/production-deployment-guide-vm-with-consul
- name: nomad installation
  when: update_nomad|bool == false
  block:
    - name: "Create user {{nomad_user}}"
      include_tasks: common/tasks/user.yml
      vars:
        create_user: "{{nomad_user}}"
        create_group: "{{nomad_group}}"
        create_usr_conf_dir: "{{nomad_conf_dir}}"

    - name: "Add nomad to docker"
      become: true
      ansible.builtin.user:
        name: nomad
        groups: docker
        state: present


    - name: Install nomad
      include_tasks: nomad_install.yml

    - name: Install nomad plugin cni
      include_tasks: nomad_plugin_cni_install.yml

    - name: Install nomad cli tool levant
      include_tasks: nomad_cli_levant_install.yml

    - name: Install nomad cli tool wander
      include_tasks: nomad_cli_wander_install.yml

    - name: Nomad config
      include_tasks: copy_copy_config_files.yml

    - name: Nomad service
      include_tasks: nomad_systemd_install.yml

- name: nomad update
  when: update_nomad|bool == true
  block:
    - name: Update nomad
      include_tasks: nomad_update.yml

    - name: Nomad config
      include_tasks: copy_copy_config_files.yml

    - name: Nomad service
      include_tasks: nomad_systemd_install.yml
  vars:
    consul_cert_path: "{{base_cert_dir}}/consul"
    consul_cert: "{{consul_cert_path}}/consul.pem"
    consul_cert_key: "{{consul_cert_path}}/consul-key.pem"
    # todo define this in common
    nomad_consul_initial_agent_token: "e95b599e-166e-7d80-08ad-aee76e7ddf19"

    nomad_cert_path: "{{base_cert_dir}}/nomad"
    nomad_cert: "{{nomad_cert_path}}/nomad.pem"
    nomad_cert_key: "{{nomad_cert_path}}/nomad-key.pem"
    nomad_cli_cert: "{{nomad_cert_path}}/nomad-cli.pem"
    nomad_data_dir: "{{service_working_dir_base}}/core/nomad/data"
    nomad_dns: "nomad.{{tls_san}}"
    nomad_encrypt_key: "4PRfoE6Mj9dHTLpnzmYD1+THdlyAo2Ji4U6ewMumpAw="
    nomad_infra_image: "{{registry_dns}}/google_containers/pause-amd64:3.1"
    nomad_servers:
      - "127.0.0.1"
      - "server.global.nomad"
      - "localhost"
      - "{{nomad_dns}}"
      - "server.{{data_center}}.nomad"
      - "server.{{host_name}}.{{data_center}}.nomad"