- name: nomad uninstall
  become: true
  when: uninstall_nomad|bool == true
  block:
    - name: stop nomad service
      failed_when: false
      service:
        name: nomad
        state: stopped
        enabled: false


    - name: "Delete nomad dir  {{nomad_data_dir}} if present"
      ansible.builtin.file:
        path: "{{nomad_data_dir}}"
        state: absent

    - name: "Delete nomad conf dir  {{nomad_conf_dir}} if present"
      ansible.builtin.file:
        path: "{{nomad_conf_dir}}"
        state: absent

    - name: "Delete nomad cert dir  {{nomad_cert_path}} if present"
      ansible.builtin.file:
        path: "{{nomad_cert_path}}"
        state: absent


    - name: "Delete nomad installation"
      ansible.builtin.file:
        path: /usr/local/bin/nomad
        state: absent
        mode: '0755'


- name : Check nomad installation present
  stat:
    path: /usr/local/bin/nomad
  register: nomadInstalled


- name: Create nomad home dir
  become: true
  file:
    path: "{{nomad_conf_dir}}"
    owner: "{{nomad_user}}"
    group: "{{nomad_group}}"
    state: directory
    mode: '0755'

- name: nomad cert install
  become: true
  when: not nomadInstalled.stat.exists or update_certificates|bool == true
  block:
    - name: install_cert handler nomad
      include_tasks: handlers/generate_nomad_certs.yml


- name: nomad install
  become: true
  when: not nomadInstalled.stat.exists
  block:

    #  Permissions
#  Nomad servers and Nomad clients have different requirements for permissions.
#  Nomad servers should be run with the lowest possible permissions.
#  They need access to their own data directory and the ability to bind to their ports.
#  You should create a nomad user with the minimal set of required privileges.
#
#  Nomad clients should be run as root due to the OS isolation mechanisms that require root privileges.
#  While it is possible to run Nomad as an unprivileged user, careful testing must be done to ensure the task drivers and
#  features you use function as expected. The Nomad client's
#  data directory should be owned by root with filesystem permissions set to 0700.
    - name: "Create nomad data dir for master if needed"
      when: is_master_host
      become: true
      file:
        path: "{{nomad_data_dir}}"
        owner: "{{nomad_user}}"
        group: "{{nomad_group}}"
        state: directory
        mode: '0755'

    - name: "Create nomad data dir for worker if needed"
      when: is_worker_host
      become: true
      file:
        path: "{{nomad_data_dir}}"
        owner: root
        group: root
        state: directory
        mode: '0700'


    - name: Download nomad binary
      get_url:
        url: https://releases.hashicorp.com/nomad/{{nomad_version}}/nomad_{{nomad_version}}_linux_amd64.zip
        dest: /tmp/nomad{{nomad_version}}_linux_amd64.zip
        owner: "{{ nomad_user }}"
        group: "{{ nomad_group }}"
        mode: 0755
        checksum: "{{nomad_checksum}}"
      register: nomad_download

    - name: "Unzip nomad archive"
      unarchive:
        src: "{{ nomad_download.dest }}"
        dest: /usr/local/bin
        copy: no
        owner: "{{ nomad_user }}"
        group: "{{ nomad_group }}"
        mode: 0755

    - name: Install nomad autocomplete for root
      shell: |
        nomad -autocomplete-install
      register: install
      changed_when: false
      # a reinstall triggers an error. Ignore this
      failed_when: install.rc > 2

    - name: Install nomad autocomplete for user
      become: false
      shell: |
        nomad -autocomplete-install
      changed_when: false
      register: install
      # a reinstall triggers an error. Ignore this
      failed_when: install.rc > 2

