- name: Install nomad systemd service
  become: true
  block:

    - name: Nomad worker auto eligtion hook service
      when: is_worker_host
      block:
        - name: Template nomad.eligtion.service.j2
          template:
            force: yes
            src: service/nomad.eligtion.service.j2
            dest: /etc/systemd/system/nomad.eligtion.service
          register: serviceconfig_eligtion

        - name: Template nomad_kill_pause_containers.sh.j2
          template:
            force: yes
            src: service/nomad_kill_pause_containers.sh.j2
            dest: "{{nomad_conf_dir}}/nomad_kill_pause_containers.sh"
          register: template_kill_pause

        - name: Template nomad_node_drain.sh.j2
          template:
            force: yes
            src: service/nomad_node_drain.sh.j2
            dest: "{{nomad_conf_dir}}/nomad_node_drain.sh"
          register: template_node_drain

        - name: "Changing perm of {{nomad_conf_dir}}/nomad_node_drain.sh"
          file: dest="{{nomad_conf_dir}}/nomad_node_drain.sh" mode=+x

        - name: "Changing perm of {{nomad_conf_dir}}/nomad_kill_pause_containers.sh"
          file: dest="{{nomad_conf_dir}}/nomad_kill_pause_containers.sh" mode=+x

        - name: enable nomad eligtion service
          service:
            name: nomad.eligtion
            enabled: yes

    - name: Template nomad.service
      template:
        force: yes
        src: service/nomad.service.j2
        dest: /etc/systemd/system/nomad.service
      register: serviceconfig



#     failed_when: install.rc > 2

