- name: "nomad plugin cni"
  become: true
  block:
    - name: "Delete nomad plugin cni dir {{plugin_dir}} if present"
      when: uninstall_nomad_plugin_cni|bool == true or update_nomad_plugin_cni|bool == true
      ansible.builtin.file:
        path: "{{plugin_dir}}"
        state: absent

    - name: "Delete consul cni plugin {{consul_cni_bin}} if present"
      when: uninstall_nomad_plugin_consul_cni|bool == true or update_nomad_plugin_consul_cni|bool == true
      ansible.builtin.file:
        path: "{{consul_cni_bin}}"
        state: absent

    - name : Check nomad plugin cni installation present
      stat:
        path: "{{cni_bin}}"
      register: cniPluginInstalled

    - name : Check nomad plugin consul cni installation present
      stat:
        path: "{{consul_cni_bin}}"
      register: consulCniPluginInstalled

    - name: "Create nomad cni plugin dir {{plugin_dir}} if needed"
      become: true
      file:
        path: "{{plugin_dir}}"
        owner: "{{nomad_user}}"
        group: "{{nomad_group}}"
        state: directory
        mode: '0755'

    - name: Install cni plugin
      when: not cniPluginInstalled.stat.exists
      block:
      - name: Download nomad plugin cni binary
        get_url:
          url: https://github.com/containernetworking/plugins/releases/download/v{{nomad_plugin_cni_version}}/cni-plugins-linux-amd64-v{{nomad_plugin_cni_version}}.tgz
          dest: "/{{download_dir}}/cni-plugins-linux-amd64-{{nomad_plugin_cni_version}}_linux_amd64.zip"
          owner: "{{ nomad_user }}"
          group: "{{ nomad_group }}"
          mode: 0755
          checksum: "{{nomad_plugin_cni_checksum}}"
        register: nomad_plugin_cni_download

      - name: "Unzip nomad plugin cni archive to {{plugin_dir}}"
        unarchive:
          src: "{{nomad_plugin_cni_download.dest}}"
          dest: "{{plugin_dir}}"
          copy: no
          owner: "{{ nomad_user }}"
          group: "{{ nomad_group }}"
          mode: 0755

      - name: Template host_bridge_network_conf.j2
        become: true
        template:
          force: yes
          src: conf/host_bridge_network_conf.j2
          dest: /etc/sysctl.d/bridge.conf

    - name: Install consul cni plugin
      when: not consulCniPluginInstalled.stat.exists
      block:
        - name: Download nomad plugin consul cni binary
          get_url:
            url: https://releases.hashicorp.com/consul-cni/{{nomad_plugin_consul_cni_version}}/consul-cni_{{nomad_plugin_consul_cni_version}}_linux_amd64.zip
            dest: "/{{download_dir}}/consul-cni_{{nomad_plugin_consul_cni_version}}_linux_amd64.zip"
            owner: "{{ nomad_user }}"
            group: "{{ nomad_group }}"
            mode: 0755
            checksum: "{{nomad_plugin_consul_cni_checksum}}"
          register: nomad_plugin_consul_cni_download

        - name: "Unzip nomad plugin consul cni archive to {{plugin_dir}}"
          unarchive:
            src: "{{nomad_plugin_consul_cni_download.dest}}"
            dest: "{{plugin_dir}}"
            copy: no
            owner: "{{ nomad_user }}"
            group: "{{ nomad_group }}"
            mode: 0755
  vars:
    plugin_dir: "/opt/cni/bin"
    consul_cni_bin: "{{plugin_dir}}/consul-cni"
    cni_bin: "{{plugin_dir}}/bridge"
