- name: volumes
  become: true
  block:
  - name: "Check if volume exists"
    register: volume
    stat:
      path: "{{item.path}}"

  - name: "Create volumes"
    become: true
    changed_when: false
    file:
      state: directory
      owner: "{{item.user | default('root')}}"
      group: "{{item.group | default('root')}}"
      mode: "{{item.mode | default('0777')}}"
      path: "{{item.path}}"

  - name: Template nomad volume
    register: template
    template:
      force: yes # replace the remote file when contents are different than the source.
      src: "{{role_path}}/../nomad/templates/conf/nomad_client_volumes.j2"
      dest: "{{nomad_conf_dir}}/nomad_volume_{{item.name}}.hcl"
      owner: "{{ nomad_user }}"
      group: "{{ nomad_group }}"

  - name: Set volume changed
    when: template.changed or volume.changed
    set_fact:
      volume_changed: true

  - name: Set volume changed default
    when: volume_changed is not defined
    set_fact:
      volume_changed: false
