---
tls_san: cloud.private
tls_san_wc:
  -  "*.{{tls_san}}"
host_name: "{{ ansible_hostname  }}"
host_ip: "{{ ansible_eth1.ipv4.address }}"
host_ips:
  - "{{ ansible_eth0.ipv4.address }}"
  - "{{ ansible_eth1.ipv4.address }}"
master_ip: "{{ hostvars[groups['masters'][0]]['ansible_host'] | default(groups['masters'][0]) }}"
worker_01_ip: "{{ hostvars[groups['workers'][0]]['ansible_host'] | default(groups['workers'][0]) }}"
registry_ip: "{{ hostvars[groups['build'][0]]['ansible_host'] | default(groups['build'][0]) }}"
registry_port: "5000"
registry_port_push: "5001"
registry_port_http: "5002"
registry_dns: "registry.{{tls_san}}"
push_registry : "{{registry_ip}}:{{registry_port_push}}"
nexus_dns: "nexus.{{tls_san}}"
security_dns: "security.{{tls_san}}"
masters: "{{ groups['masters'] }}"
workers: "{{ groups['workers'] }}"
builders: "{{ groups['build'] }}"
worker_names: "{{groups['workers']|map('extract', hostvars, ['ansible_hostname']) |list}}"
worker_index: "{{groups['workers'].index(inventory_hostname)}}"

is_local_host: "{{ inventory_hostname in groups['localhost'] }}"
is_build_host: "{{ inventory_hostname in groups['build'] }}"
is_master_host: "{{ inventory_hostname in groups['masters'] }}"
is_worker_host: "{{ inventory_hostname in groups['workers'] }}"
is_master_0: "{{hostvars[groups['masters'][0]]['ansible_hostname'] == host_name}}"

vault_dns: "vault.{{tls_san}}"
vault_ip: "{{ hostvars[groups['masters'][0]]['ansible_host'] | default(groups['masters'][0]) }}"
vault_hosts:
  - "127.0.0.1"
  - "localhost"
  - "{{vault_dns}}"
  - "{{vault_ip}}"



core_realm: "nomadder"
# consul and nomad datacenter name
data_center: "nomadder1"
#cert path on nodes
cert_path_master_0: /etc/ssl/private/cloudlocal
#TODO rename to ca_os_trust_store
ca_cert_path: /usr/local/share/ca-certificates/cloudlocal
cluster_intermediate_ca_bundle: "{{ca_cert_path}}/cluster-ca-bundle.pem"
# cert path on local host
#TODO this should not be necessary anymore
local_ca_copy_path: "{{role_path}}/tmp/certs"
local_cert_gen_path: "{{local_ca_copy_path}}/{{host_name}}"
local_ca_cert_conf: "{{role_path}}/../certificates_generate/files/cfssl/config.json"
local_ca_cert_path: "{{role_path}}/../certificates_generate/files/certs/ca"
local_cluster_ca_cert_path: "{{role_path}}/../certificates_generate/files/certs/cluster-ca"
service_working_dir_base:  /opt/services
master_0_job_dir:  /opt/nomadjobs
nomad_volumes_dir:  /opt/nomadvolumes
base_cert_dir: /etc/opt/certs
notify_cert_change: false


vault_group: vault
vault_user: vault
vault_conf_dir: "/etc/vault.d"

consul_group: consul
consul_user: consul
consul_conf_dir: "/etc/consul.d"

nomad_group: nomad
nomad_user: nomad
nomad_conf_dir: "/etc/nomad.d"

# enables traefik middlware for oauth authentication
enable_oauth_middleware: true