vault_version: "1.11.1"
vault_checksum: "sha256:aa2ed532d9a0ecc8635fed63cb3fb6de472b4c01ca622a9a199cd92a046bc73a"
uninstall_vault: "{{uninstall_all or false }}"
update_vault: "{{update_all or false }}"


consul_version: "2.0.1"
consul_checksum: "sha256:f8189736b05e3fe42d27dd83dfbd3a6d7e44b5669b2e51684362e9c1639babe0"
uninstall_consul: "{{uninstall_all or false }}"
update_consul: "{{update_all or false }}"

consul_template_version: "0.42.0"
consul_template_checksum: "sha256:94d5044b822c5219bb116916b8d4d2545630e6ce0e1639ddd25309a26cf62ff2"
update_consul_template: "{{update_all or false }}"
uninstall_consul_template: "{{uninstall_all or false }}"

nomad_version: "2.0.3"
nomad_checksum: "sha256:8455d5691de4cb451e9443282f1c0171570b480737fc6386992638c52a4795e4"
# Nomad 2.0.1 has a bug with the job ui view
#nomad_version: "2.0.1"
#nomad_checksum: "sha256:cf5d820b5dc3fcd1ceb8baf3afab46e3a52a56fc3016fcdaed0505f531a39540"

uninstall_nomad: "{{uninstall_all or false }}"
update_nomad: "{{update_all or false }}"

version_envoy: 1.38.3

nomad_plugin_cni_version: "1.9.1"
nomad_plugin_cni_checksum: "sha256:b98f74a0f8522f0a83867178729c1aa70f2158f90c45a2ca8fa791db1c76b303"
uninstall_nomad_plugin_cni: "{{uninstall_all or false }}"
update_nomad_plugin_cni: "{{update_all or false }}"

#nomad_plugin_consul_cni_version: "1.9.6"
#nomad_plugin_consul_cni_checksum: "sha256:80208dbf81fc6a0fd3786683c8f1042b559e251cebc6bcdeb56ff3e13a1ab546"
nomad_plugin_consul_cni_version: "2.0.0"
nomad_plugin_consul_cni_checksum: "sha256:8d6367f4e2966bd8ec54d14b5005cccf69d537c9ceb80bdf5c2aa898ab0783a0"
uninstall_nomad_plugin_consul_cni: "{{uninstall_all or false }}"
update_nomad_plugin_consul_cni: "{{update_all or false }}"


nomad_cli_levant_version: "0.3.2"
nomad_cli_levant_checkusum: "sha256:1e06180f8d8327e721e2ad4c9637d1f391034a22709473b8ed8ee19f1cad1570"
uninstall_cli_levant: "{{uninstall_all or false }}"
update_cli_levant: "{{update_all or false }}"

version_wander: "1.1.0"
nomad_cli_wander_checkusum: "sha256:1d82191134ac213a36d1cee0aa9a91fb86de4344cce3649a2f45c5e25f58a1d1"
uninstall_cli_wander: "{{uninstall_all or false }}"
update_cli_wander: "{{update_all or false }}"


version_cfssl: 1.6.5
update_cfssl: "{{update_all or false }}"

version_docker: "29.6.0"
uninstall_docker: false

# docker-compose is not used anymore use docker compose plugin instead
#version_docker_compose: "2.37.3"
#uninstall_compose: false

update_certificates: false

version_nexus: "3.93.1"
version_nexus_initlzr: "1.0.8"
update_nexus: false


version_busy_box_init_container: "1.37.0"
version_multi_stage_apline_container: "3.17.2"
version_grafana_agent_container: "0.44.3"

version_grafana_alloy: "1.17.0"

uninstall_grafana_alloy : "{{uninstall_all or false }}"
# Update is handled by grafana role specify only the new version
#update_grafana_alloy : "{{update_all or false }}"1

validityCaCert: "87600h"
# 1h less than validityCaCert
validityClusterCa: "87599h"
# 1h less than validityClusterCa
validityServerCert: "87598h"
# 1h less than validityServerCert
validityClientCert: "87597h"
