- name: Install cli tools
  block:
    - name: "Install nats cli v {{version_nats_cli}}"
      import_tasks: install_nats_cli.yml
    - name: "Install nats cli nsc v {{version_nats_cli_nsc}}"
      import_tasks: install_nats_nsc.yml

  vars:
    - version_nats_cli: "0.1.1"
    - update_nats_cli: false
    - version_nats_cli_nsc: "2.8.5"
    - nats_cli_nsc_checksum: "sha256:c5af53624f52cfbd2732bfdd40c3a0371a921ff11d5d097ede8946c4d83c4207  "
    - update_nats_cli_nsc: false
    - uninstall_nats_cli_nsc: false