- name: Install cli tools
  block:
    - name: "Install nats cli v {{version_nats_cli}}"
      import_tasks: install_nats_cli.yml
    - name: "Install nats cli nsc v {{version_nats_cli_nsc}}"
      import_tasks: install_nats_nsc.yml

  vars:
    - version_nats_cli: "0.1.1"
    - update_nats_cli: false
    - version_nats_cli_nsc: "2.8.1"
    - nats_cli_nsc_checksum: "sha256:9e084f84e33d32cddbdfb0afc82cfeefa78e90249efda28c507d744d5a5aebfc  "
    - update_nats_cli_nsc: false
    - uninstall_nats_cli_nsc: false