- name: Install cli tools
  block:
    - name: "Install nats cli v {{version_nats_cli}}"
      import_tasks: install_nats_cli.yml
    - name: "Install nats cli nsc v {{version_nats_cli_nsc}}"
      import_tasks: install_nats_nsc.yml
    - name: "Install grafana dash n-grab  v {{version_gdg_cli}}"
      import_tasks: install_gdg_cli.yml

  vars:
      - version_nats_cli: "0.1.5"
      - update_nats_cli: "{{update_all or false }}"
      - version_nats_cli_nsc: "2.9.0"
      - nats_cli_nsc_checksum: "sha256:4dfea5a9a69ae9c940e6fd7881ddbc4c2af91c00131e099fa9fd6e58c49e153a  "
      - update_nats_cli_nsc: "{{update_all or false }}"
      - uninstall_nats_cli_nsc: "{{uninstall_all or false }}"
        # grafana desktop manager
      - version_gdg_cli: "0.5.2"
      - update_gdg_cli: "{{update_all or false }}"
      - uninstall_gdg_cli: "{{update_all or false }}"