- name: Install cli tools
  block:
    - name: "Install nats cli v {{version_nats_cli}}"
      import_tasks: install_nats_cli.yml
    - name: "Install nats cli nsc v {{version_nats_cli_nsc}}"
      import_tasks: install_nats_nsc.yml
    - name: "Install grafana dash n-grab  v {{version_gdg_cli}}"
      import_tasks: install_gdg_cli.yml

  vars:
      - version_nats_cli: "0.2.2"
      - update_nats_cli: "{{update_all or false }}"
      - version_nats_cli_nsc: "2.11.0"
      - nats_cli_nsc_checksum: "sha256:a1ca11ca1080c35fbfb908b6241e41369cd289030d3d410ac86f85cc096e0169  "
      - update_nats_cli_nsc: "{{update_all or false }}"
      - uninstall_nats_cli_nsc: "{{uninstall_all or false }}"
        # grafana desktop manager
      - version_gdg_cli: "0.5.2"
      - update_gdg_cli: "{{update_all or false }}"
      - uninstall_gdg_cli: "{{update_all or false }}"
