- name: "Update certificates {{ update_certificates|bool == true }} "
  when: update_certificates|bool == true
  block:
    - name: "Delete import certs on host"
      become: true
      file:
        state: absent
        path: "{{ca_cert_path}}"

    - name: "Refresh trust store "
      become: true
      shell: update-ca-certificates
      register: caimport

    - name: "Deleted certs"
      debug:
        msg: "{{ caimport }}"
