- name: Set local cert path
  set_fact:
    #cert path on nodes
    ca_cert_path: /usr/local/share/ca-certificates/cloudlocal
    # cert path on local host
    local_ca_cert_path: "{{role_path}}/../certificates_generate/files/certs/ca"


- name: "Update certificates {{ update_certificates|bool == true }} "
  become: true
  file:
    state: absent
    path: "{{ca_cert_path}}"

- name: "Create certificate folder if needed "
  become: true
  file:
    state: directory
    path: "{{ca_cert_path}}"

- name : "Check if ca certificate exist on node"
  stat:
    path: "{{ca_cert_path}}/ca.crt"
  register: ca


- name: Install certificates
  when: not ca.stat.exists
  block:

    - name: "Copy ca certs to {{ ca_cert_path }}"
      become: true
      ansible.posix.synchronize:
        src: "{{local_ca_cert_path}}"
        dest: "{{ ca_cert_path }}"

    - name: "Set permissions on {{ca_cert_path}}"
      become: true
      shell: |
        cp {{ca_cert_path}}/ca/ca.pem {{ca_cert_path}}/ca/ca.crt

        find  {{ca_cert_path}} -type d -exec chmod 755 {} +
        find {{ca_cert_path}} -type d -exec chown root:root {} +
        find {{ca_cert_path}} -type f -exec chmod 644 {} +
        find  {{ca_cert_path}} -type f -exec chown root:root {} +

      register: caimports

    - name: "Import PKI "
      delay: 0
      async: 1
      poll: 1
      become: true
      shell: update-ca-certificates
      args:
        chdir: "{{ ca_cert_path }}"
      register: caimports

    - debug:
        msg: "{{ caimports }}"


    # Don't use handler anymore for this task list.
    # Because it is only triggered if certs deleted or not exists
#    - name: Reboot on cert change
#      become: true
#      reboot:
#        reboot_timeout: 3600