{
 "title": "LogsTest",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "ingress",
    "label": "ingress",
    "query": {}
   },
   {
    "name": "job_types",
    "label": "job_types",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Log level distribution for job type  $__interval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$job_types ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "repeat": "job_types",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({ingress=\"$ingress\",job_type=~\"$job_types\"}  [$__interval]))",
     "legendFormat": "{{level}} "
    }
   ]
  },
  {
   "title": "Log distrubution",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({ingress=\"$ingress\"}  [1w]))",
     "legendFormat": "{{level}} "
    }
   ]
  },
  {
   "title": "Log distrubution in $__interval",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 4 },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({ingress=\"$ingress\"}  [$__interval]))",
     "legendFormat": "{{level}} "
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": " ",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job_type, stack,job,level) (count_over_time({ingress=\"$ingress\"} [1w] ))",
       "resolution": 1
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Panel",
     "type": "logs",
     "gridPos": { "h": 25, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "{ingress=\"$ingress\", job_type=~\"$job_types\"} |= `` | json | line_format `{{.job}}@{{.host_name}} [{{.log_levelEmoji}}  {{.level}}] [{{.tags}}]  {{.message}}`"
      }
     ]
    }
   ]
  }
 ]
}