- name: Certificates
  block:
    - name: "Update certificates {{ update_certificates|bool == true }} "
      become: true
      file:
        state: absent
        path: "{{vault_cert_path}}"
      when: update_certificates|bool == true

    - name : "Check if vault certificate exist on node -> {{vault_cert_path}}/vault.pem"
      stat:
        path: "{{vault_cert_path}}/vault.pem"
      register: cert

- name: Install certificates
  when: not cert.stat.exists
  block:

    - name: "Change file ownership, group and permissions for {{vault_cert_path}}"
      become: true
      ansible.builtin.file:
        path: "{{vault_cert_path}}"
        owner: vault
        group: vault
        state: directory
        mode: '0755'

    - name: "Create Vault certificate work dir if needed"
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{local_cert_gen_path}}"
        state: directory

    - name: Template vault_cert.json
      delegate_to: localhost
      template:
        force: yes
        src: vault_cert.j2
        dest: "{{local_cert_gen_path}}/vault_cert.json"


    - name: "Generate vault certificates in {{local_cert_gen_path}}"
      delegate_to: localhost
      shell: |
        cfssl gencert \
          -ca ../cloudlocal/cluster-ca/cluster-ca.pem \
          -ca-key ../cloudlocal/cluster-ca/cluster-ca-key.pem \
          -config {{local_ca_cert_conf}} \
          -profile server vault_cert.json | cfssljson -bare vault
      args:
        chdir: "{{local_cert_gen_path}}"

    - name: "Copy certificate to {{vault_cert}}"
      become: true
      ansible.builtin.copy:
        src: "{{local_cert_gen_path}}/vault.pem"
        dest: "{{vault_cert}}"
        owner: "{{vault_user}}"
        group: "{{vault_group}}"
        mode: '0644'

    - name: "Copy certificate key to {{vault_cert_key}}"
      become: true
      ansible.builtin.copy:
        src: "{{local_cert_gen_path}}/vault-key.pem"
        dest: "{{vault_cert_key}}"
        owner: "{{vault_user}}"
        group: "{{vault_group}}"
        mode: '0644'

    - name: restart vault service
      ignore_errors: true
      become: true
      service:
        name: vault
        state: restarted


