---
# This setup is inspired by  https://github.com/suikast42/AnsibleVaultRole forked from  https://github.com/MiteshSharma/AnsibleVaultRole
# The original setup copies the vault keys to the local machine. This changed setup leave the keys in master[0]

#- name: get service facts
#  service_facts:
#- debug:
#    var: ansible_facts.services['ufw.service']

- name: Vault install variables
  block:

  - name: Set local cert path
    set_fact:
      #cert path on nodes
      vault_cert_copy_path: /etc/opt/certs
      vault_cert_path: /etc/opt/certs/vault
      # cert path on local host
      local_ca_cert_path: "{{role_path}}/tmp/certs"
      cacheable: true

  - name: Set local cert files
    set_fact:
      # Persistence path on vaults' host
      vault_data_dir: "/opt/deployments/core/vault/data"
      vault_cert: "{{vault_cert_path}}/vault.pem"
      vault_cert_key: "{{vault_cert_path}}/vault-key.pem"
      ca_cert: "{{ca_cert_path}}/cluster-ca/cluster-ca.pem"
      cacheable: true

  - name: Set init vars
    set_fact:
      unseal_keys_dir_output: "{{vault_data_dir}}/unsealKey"
      root_token_dir_output: "{{vault_data_dir}}/rootKey"
      vault_unseal_bin_dir: "{{vault_data_dir}}/cbin"
      cacheable: true

- name: Vault installation
  block:

  - name: "Create vault user"
    import_tasks: user.yml

  - name: "Vault certificates"
    import_tasks: certificates.yml

  - name: "Vault installation"
    import_tasks: vault_install.yml


- name: Vault init
  block:

    - name: "Vault initialization"
      import_tasks: vault_init.yml

    - name: "Vault init pki"
      import_tasks: vault_init_pki.yml
