---
# This setup is inspired by  https://github.com/suikast42/AnsibleVaultRole forked from  https://github.com/MiteshSharma/AnsibleVaultRole
# The original setup copies the vault keys to the local machine. This changed setup leave the keys in master[0]

#- name: get service facts
#  service_facts:
#- debug:
#    var: ansible_facts.services['ufw.service']

- name: Vault install variables
  block:

  - name: Set local cert path
    set_fact:
      #cert path on nodes
      vault_cert_path: "{{ base_cert_dir}}/vault"
      cacheable: true

  - name: Set local cert files
    set_fact:
      # Persistence path on vaults' host
      vault_data_dir: "{{systemd_install_dir}}/vault/data"
      vault_cert: "{{vault_cert_path}}/vault.pem"
      vault_cert_key: "{{vault_cert_path}}/vault-key.pem"
      cacheable: true

  - name: Set init vars
    set_fact:
      unseal_keys_dir_output: "{{vault_data_dir}}/unsealKey"
      root_token_dir_output: "{{vault_data_dir}}/rootKey"
      vault_unseal_bin_dir: "{{vault_data_dir}}/cbin"
      cacheable: true

- name: Vault installation
  block:

  - name: "Create user {{nomad_user}}"
    include_tasks: common/tasks/user.yml
    vars:
      create_user: "{{vault_user}}"
      create_group: "{{vault_group}}"
      create_usr_conf_dir: "{{vault_conf_dir}}"


  - name: "Vault installation"
    import_tasks: vault_install.yml


- name: Vault init
  block:

    - name: "Vault initialization"
      import_tasks: vault_init.yml

    - name: "Vault init pki"
      import_tasks: vault_init_pki.yml
