---

- name: Certificates
  delegate_to: localhost
  run_once: true
  block:
  - name: "Update certificates {{ update_certificates|bool == true }} "
    when: update_certificates|bool == true
    file:
      state: absent
      path: "{{role_path}}/files/certs"

  - name : "Check if certificates are generated"
    stat:
      path: "{{role_path}}/files/certs/ca/ca.pem"
    register: caCert

  - debug:
      msg: "Certificates already generated {{ caCert.stat.exists }}"

  - name: "Generate certificates"
    import_tasks: certificates.yml
    when:  not caCert.stat.exists
