- name: Localhost setup
  block:

  - name: "Delete download dir"
    become: true
    when: delete_downloads |bool == true
    ansible.builtin.file:
      path: "{{download_dir}}"
      state: absent

  - name: "Create download dir"
    become: true
    ansible.builtin.file:
      path: "{{download_dir}}"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      state: directory
      mode: '0755'

#  - name: Install pip modules
#    pip:
#      name:
#        - pexpect
#        - docker
#      extra_args: --user
  - name: "Install pip modules"
    become: true
    apt:
      name:
        - python3-pexpect
        - python3-docker
  # Install secint on localhost
  # Need for autoconfigure consul
  # See https://github.com/hashicorp/learn-consul-docker/tree/main/datacenter-deploy-auto-config/secint
  - name: Install secint
    shell: |
      rm -rf ./secint
      git clone https://github.com/banks/secint
      cd secint
      go build 
    failed_when: build.rc > 0
    register: build

  - name: Move secint to /usr/local/bin
    become: true
    shell: |
      cd secint
      mv secint /usr/local/bin
      cd ..
      rm -R secint
#    failed_when: install.rc > 0
#    args:
#      creates: /usr/local/bin/secint
#    register: build
#



  - name: "Delete vim hcl dir  ~/.vim/pack/jvirtanen/start if present"
    when: update_vim_hcl|bool == true
    ansible.builtin.file:
      path: "~/.vim/pack/jvirtanen/start"
      state: absent

  - name: "vim hcl"
    delay: 0
    async: 300
    poll: 1
    shell: |
      mkdir -p ~/.vim/pack/jvirtanen/start
      cd ~/.vim/pack/jvirtanen/start
      git clone https://github.com/jvirtanen/vim-hcl.git
    args:
      creates: ~/.vim/pack/jvirtanen/start

  - name: Template zshenv
    when: is_devnode
    template:
      force: yes
      src: .zshenv
      dest: "{{ ansible_env.HOME }}/.zshenv"
      group: "{{ansible_ssh_user}}"
      owner: "{{ansible_ssh_user}}"
      mode: 0644

  - name: Ensure ~/.profile sources ~/.zshenv for graphical sessions
    when: is_devnode
    ansible.builtin.lineinfile:
      path: "{{ ansible_env.HOME }}/.profile"
      # The 'line' is the exact text we want to appear
      line: 'if [ -f "$HOME/.zshenv" ]; then . "$HOME/.zshenv"; fi'
      # The 'regexp' ensures that if a similar line exists, it is replaced instead of duplicated
      regexp: '^if \[ -f "\$HOME/.zshenv" \].*'
      state: present
      create: yes
      firstmatch: yes
      insertafter: EOF
      mode: '0644'

  vars:
    # Override the download_dir for localhost
    download_dir: "{{ansible_env.HOME}}/Downloads"
  tags:
    - localhost

