- name: Localhost setup
  block:

  - name: "Delete download dir"
    become: true
    when: delete_downloads |bool == true
    ansible.builtin.file:
      path: "{{download_dir}}"
      state: absent

  - name: "Create download dir"
    become: true
    ansible.builtin.file:
      path: "{{download_dir}}"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      state: directory
      mode: '0755'

  - name: Install pip modules
    pip:
      name:
        - pexpect
        - docker
      extra_args: --user

  # Install secint on localhost
  # Need for autoconfigure consul
  # See https://github.com/hashicorp/learn-consul-docker/tree/main/datacenter-deploy-auto-config/secint
  - name: Install secint
    shell: |
      git clone https://github.com/banks/secint
      cd secint
      go build 
      sudo mv secint /usr/local/bin
      cd ..
      rm -R secint
    args:
      creates: /usr/local/bin/secint # oh-my-posh is already installed
#    register: build
#
  - name: "Debug Delete protoc"
    debug:
      msg: "update_all: {{update_all}}, uninstall_protoc:{{uninstall_protoc}}"

  - name: "Delete protoc"
    become: true
    when: uninstall_protoc|bool == true
    shell: |
      rm -fr /usr/local/bin/protoc*
      rm -fr /usr/local/bin/include
      rm -fr /tmp/protoc
      rm -fr /usr/local/bin/buf


  - name: "Download protoc v{{version_protoc}}"
    get_url:
      url: https://github.com/protocolbuffers/protobuf/releases/download/v{{version_protoc}}/protoc-{{version_protoc}}-linux-x86_64.zip
      dest: "/{{download_dir}}/protoc_{{version_protoc}}.tgz"
      mode: 0755
    register: protoc_download

  - name: "Create tmp dir"
    file:
      path: "/tmp/protoc"
      state: directory
      mode: '0755'

  - name: "Unzip protoc"
    become: true
    unarchive:
      src: "{{protoc_download.dest}}"
      dest: "/tmp/protoc"
      copy: no

#  - name: "Install protoc in /usr/local/bin"
#    register: installProto
#    failed_when: installProto.rc != 0
#    shell: |
#      go install google.golang.org/protobuf/cmd/protoc-gen-go@v{{version_proto_gen}}
#      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v{{version_proto_grpc}}
#      go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v{{version_proto_grpc_gateway}}
#      go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v{{version_proto_openapi}}
#      curl -sSL "https://github.com/bufbuild/buf/releases/download/v{{version_proto_buf_cli}}/buf-$(uname -s)-$(uname -m)" -o buf
#      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-go  /usr/local/bin
#      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-go-grpc  /usr/local/bin
#      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-grpc-gateway  /usr/local/bin
#      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-openapiv2  /usr/local/bin
#      sudo mv bin/protoc /usr/local/bin
#      sudo mv include   /usr/local/bin/include
#      sudo mv buf  /usr/local/bin
#      chmod +x  /usr/local/bin/buf
#    args:
#      chdir: "/tmp/protoc"
#      creates: /usr/local/bin/protoc

  - name: "Install protoc in /usr/local/bin"
    register: installProto
    failed_when: installProto.rc != 0
    shell: |
      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v{{version_proto_grpc}}
      sudo mv /home/{{ansible_user}}/go/bin/protoc-gen-go-grpc  /usr/local/bin
      
      go install google.golang.org/protobuf/cmd/protoc-gen-go@v{{version_proto_gen}} 
      sudo mv bin/protoc /usr/local/bin
      sudo mv include   /usr/local/bin/include
      
      go install github.com/fullstorydev/grpcurl/cmd/grpcurl@v{{version_proto_grpc_curl}}
      sudo mv grpcurl   /usr/local/bin
      
      go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@v{{version_proto_buf_connect}}
      sudo mv protoc-gen-connect-go   /usr/local/bin
      
      curl -sSL "https://github.com/bufbuild/buf/releases/download/v{{version_proto_buf_cli}}/buf-$(uname -s)-$(uname -m)" -o buf
      sudo mv buf  /usr/local/bin
      chmod +x  /usr/local/bin/buf
    args:
      chdir: "/tmp/protoc"
      creates: /usr/local/bin/protoc
  vars:
    # Override the download_dir for localhost
    download_dir: "/home/{{ansible_user}}/downloads"
  tags:
    - localhost