- name: Localhost setup
  block:

  - name: Install pip modules
    pip:
      name:
        - pexpect
        - docker
      extra_args: --user

  # Install secint on localhost
  # Need for autoconfigure consul
  # See https://github.com/hashicorp/learn-consul-docker/tree/main/datacenter-deploy-auto-config/secint
  - name: Install secint
    shell: |
      git clone https://github.com/banks/secint
      cd secint
      go build 
      sudo mv secint /usr/local/bin
      cd ..
      rm -R secint
    args:
      creates: /usr/local/bin/secint # oh-my-posh is already installed
#    register: build
#
#  - name: "Debug install secint"
#    debug:
#      msg: "{{build}}"

  - name: Install damon nomad util
    become: true
    shell: |
      git clone https://github.com/hashicorp/damon.git
      cd damon
      go build ./cmd/damon
      mv damon /usr/local/bin
    args:
      chdir: /tmp
      creates: /usr/local/bin/damon # oh-my-posh is already installed

  tags:
    - localhost