- name: Deploy core stack
  when: is_master_0
  run_once: true
  block:
    - name: "Build grafana v {{version_grafana}}"
      import_tasks: build_grafana.yml

    - name: "Build nats_prometheus_exporter v {{version_nats_prometheus_exporter_nomadder}}"
      import_tasks: build_nats_exporter.yml


    - name: "Create {{stack_deployment_dir}} if needed"
      become: true
      file:
        state: directory
        mode: '0755'
        path: "{{stack_deployment_dir}}"

    - name: "Deploy observability stack"
      import_tasks: deploy_observability.yml

  vars:
    - stack_name: "stack/observability"
    - docker_build_dir: "/tmp/dockerbuild"
    - nomad_cli_cert: "{{base_cert_dir}}/nomad/nomad-cli.pem"
    - nomad_cli_cert_key: "{{base_cert_dir}}/nomad/nomad-cli-key.pem"
    - version_grafana: "10.2.2"
    - version_grafana_nomadder: "{{version_grafana}}.1"
    - version_grafana_mimir: "2.10.4"
    - version_grafana_loki: "2.9.2"
    - version_grafana_tempo: "2.3.1"
    - version_nats_server: "2.10.7"
    - version_logunifer: "0.2.5"
    - version_blackbox_exporter: "0.24.0"
    - version_nats_prometheus_exporter: "0.13.0"
    - version_nats_prometheus_exporter_nomadder: "{{version_nats_prometheus_exporter}}.0"
    - stack_deployment_dir: "{{master_0_job_dir}}/observability"