- name: Keycloak docker build
  run_once: true
  block:
  - name: "Search for {{registry_ip}}/{{stack_name}}/keycloak:{{version_keycloak_nomadder}} in nexus"
    uri:
    # url :"https://{{nexus_dns}}/service/rest/v1/search?repository=dockerLocal&format=docker&name=stack/core/keycloak&version=19.0.2.0"
      # In the first installation phase traefik is not available. Thus, we use the ip here.
      url: "http://{{registry_ip}}:{{registry_port_http}}/service/rest/v1/search?repository=dockerLocal&format=docker&name={{stack_name}}/keycloak&version={{version_keycloak_nomadder}}"
      method: GET
      #Get json content back
#      return_content: true
      headers:
        Content-Type: application/json
#      user: "{{nexus_username}}"
#      password: "{{nexus_password}}"
#      force_basic_auth: yes
      status_code:
        - 200
    register: nexus_response

  - name: "Nexus response"
    debug:
      msg: "{{nexus_response}}"

  - name: "Set fact image exists on nexus {{ nexus_response.json['items']|length == 1}}"
    set_fact:
      image_exists_on_nexus: "{{ nexus_response.json['items']|length == 1}}"

  - name: Image build
    when: not image_exists_on_nexus
    block:
    - name: "Create docker build dir {{docker_build_dir_keycloak}} if needed"
      file:
        path: "{{docker_build_dir_keycloak}}"
        state: directory

    - name: Template dockerfile keycloak
      template:
        force: yes
        src: DockerfileKeycloak
        dest: "{{docker_build_dir_keycloak}}/Dockerfile"

    - name: Template keycloak nomadder-realm.json
      template:
        force: yes
        src: nomadder-realm.json
        dest: "{{docker_build_dir_keycloak}}/nomadder-realm.json"

    - name: "Login {{registry_dns}}"
      # do not trigger a change
      changed_when: false
      community.docker.docker_login:
        registry_url: "{{registry_dns}}"
        username: "admin"
        password: "cloudmaster"
        reauthorize: yes

    - name: "Build and push keycloak image v {{version_keycloak_nomadder}}"
      community.docker.docker_image:
        build:
          path: "{{docker_build_dir_keycloak}}"
        name: "{{registry_dns}}/{{stack_name}}/keycloak"
  #      repository: "{{registry_dns}}"
        tag: "{{version_keycloak_nomadder}}"
        push: yes
        source: build

  always:
    - name : Finally
      block:
        - name: "Delete {{docker_build_dir_keycloak}}"
          become: true
          file:
            path: "{{docker_build_dir_keycloak }}"
            state: absent
        - name: "Logout {{registry_dns}}"
          # do not trigger a change
          changed_when: false
          community.docker.docker_login:
            state: absent
            registry_url: "{{registry_dns}}"

  vars:
    - docker_build_dir_keycloak: "{{docker_build_dir}}/keycloak"