- name: Template registry.json
  delegate_to: localhost
  template:
    force: yes
    src: registry.j2
    dest: "{{role_path}}/files/registry.nomad"

- name: "Copy registry.nomad"
  become: true
  copy:
    force: true
    src: registry.nomad
    dest: "{{core_deployment_dir}}/registry.nomad"
    mode: '0755'


- name: Create job
  community.general.nomad_job:
    # host: "{{masters[0]}}"
    client_cert: "{{nomad_cli_cert}}"
    client_key: "{{nomad_cli_cert_key}}"
    host: localhost
    state: present
    force_start: true
    #        content: "{{ job.content | b64decode }}"
    content: "{{ lookup('ansible.builtin.file', '{{role_path}}/files/registry.nomad') }}"
    timeout: 120

