- name: Deploy core stack
  when: is_master_0
  run_once: true
  block:
    - name: "Build keycloak v {{version_keycloak}}"
      import_tasks: build_keycloak.yml

    - name: "Create {{core_deployment_dir}} if needed"
      become: true
      file:
        state: directory
        mode: '0755'
        path: "{{core_deployment_dir}}"

    - name: "Deploy traefik v {{version_traefik}}"
      import_tasks: deploy_ingress.yml

    - name: "Deploy keycloak v {{version_keycloak}}"
      import_tasks: deploy_security.yml
  vars:
    - stack_name: "stack/core"
    - docker_build_dir: "/tmp/dockerbuild"
    - nomad_cli_cert: "{{base_cert_dir}}/nomad/nomad-cli.pem"
    - nomad_cli_cert_key: "{{base_cert_dir}}/nomad/nomad-cli-key.pem"
    - version_traefik: "2.8.4"
    - version_keycloak: "19.0.2"
    - core_deployment_dir: "{{master_0_job_dir}}/core"

