- name: Deploy core stack
  when: is_master_0
  run_once: true
  block:
    - name: "Create {{core_deployment_dir}} if needed"
      become: true
      file:
        state: directory
        mode: '0755'
        path: "{{core_deployment_dir}}"


    - name: "Deploy traefik v {{version_traefik}}"
      import_tasks: deploy_ingress.yml

    - name: "Wait until nexus is available over ingress controller"
      uri:
        url: 'https://nexus.{{tls_san}}'
        return_content: yes
        validate_certs: no
        status_code:
          - 200
      until: uri_output.status == 200
      retries: 60000 # Retries for 24 * 5 seconds = 120 seconds = 2 minutes
      delay: 5 # Every 5 seconds
      register: uri_output

    - name: "Build keycloak v {{version_keycloak}}"
      import_tasks: build_keycloak.yml


    - name: "Deploy keycloak v {{version_keycloak}}"
      import_tasks: deploy_security.yml

    - name: "Deploy minio {{version_minio}}"
      import_tasks: deploy_minio.yml

  vars:
    stack_name: "stack/core"
    docker_build_dir: "/tmp/dockerbuild"
    nomad_cli_cert: "{{base_cert_dir}}/nomad/nomad-cli.pem"
    nomad_cli_cert_key: "{{base_cert_dir}}/nomad/nomad-cli-key.pem"
    version_traefik: "3.5.3"
    version_keycloak_metrics_spi: "2.5.3"
    version_keycloak: "26.4.2"
    version_keycloak_nomadder: "{{version_keycloak}}.0"
    version_mesosphere: "3.1.0"
    version_postgres_keycloak: "17.5"
    core_deployment_dir: "{{master_0_job_dir}}/core"
