collections:
  - name: community.docker
    version: "5.2.0"
    # Needs for rsync
  - name: ansible.posix
    version: "2.2.0"
    # nomad_job
  - name: community.general
    version: "13.0.1"
  - name: grafana.grafana
    version: "6.1.0"
