collections:
  - name: community.docker
    version: "5.0.6"
    # Needs for rsync
  - name: ansible.posix
    version: "2.1.0"
    # nomad_job
  - name: community.general
    version: "12.4.0"
  - name: grafana.grafana
    version: "6.0.6"
