server:
  log_level: info

metrics:
  wal_directory: "{{grafana_agent_working_dir}}/wal"

  configs:
    - name: agent
      scrape_configs:
        - job_name: agent
          static_configs:
            - targets: ["127.0.0.1:12345"]
      remote_write:
        - url: http://mimir.service.consul:9009/api/v1/push