server:
  log_level: info

metrics:
  wal_directory: "{{grafana_agent_working_dir}}/wal"
  global:
    scrape_interval: 10s
    remote_write:
      - url: http://mimir.service.consul:9009/api/v1/push
#        headers:
#          X-Scope-OrgID: 1


#logs:
#  configs:
#    - name: default
#      clients:
#        - url:  http://loki.service.consul:3100/api/v1/push
#      positions:
#        filename: "{{grafana_agent_working_dir}}/logpos/positions.yaml"
#      target_config:
#        sync_period: 10s
#      scrape_configs:
#        - job_name: integrations/docker
#          docker_sd_configs:
#            - host: unix:///var/run/docker.sock
#              refresh_interval: 5s
#          relabel_configs:
#            - action: replace
#              replacement: integrations/docker
#              source_labels:
#                - __meta_docker_container_id
#              target_label: job
#            - source_labels:
#                - __meta_docker_container_name
#              regex: '/(.*)'
#              target_label: container
#            - source_labels:
#                - __meta_docker_container_log_stream
#              target_label: stream


traces:
  configs:
    - name: default
      remote_write:
        - endpoint: http://tempo-otlp-grpc.service.consul:4317
#          headers:
#            X-Scope-OrgID: 1
          insecure: true
      receivers:
        jaeger:
          protocols:
            thrift_http:


integrations:
  agent:
    enabled: true
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance

  node_exporter:
    enabled: true
    relabel_configs:
      - action: replace
        source_labels:
          - agent_hostname
        target_label: instance

#  cadvisor:
#    enabled: true
#    docker_only: true
#    instance: localhost:9090
#    relabel_configs:
#      - action: replace
#        replacement: integrations/docker
#        target_label: job