#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

timezone= "Etc/UTC"

# Vector's API (disabled by default)
# Enable and try it out with the `vector top` command
[api]
enabled = true
# address = "127.0.0.1:8686"

## Log sources begin
[sources.source_internal_logs]
type = "internal_logs"

[sources.source_journald]
type = "journald"
current_boot_only = true
exclude_units = ["vector","docker","containerd","nomad_event_sink"]
exclude_matches = { }
include_units = [ ]
include_matches = { }

[sources.source_journald_logfmt]
type = "journald"
current_boot_only = true
exclude_units = []
exclude_matches = { }
include_units = ["docker","containerd","nomad_event_sink"]
include_matches = { }


{% if is_master_host  %}
[sources.source_nomad_events]
type = "http"
address = "127.0.0.1:3333" # required
decoding.codec = "json"
{% endif %}


## Log sources END

## Logfmt logunifer transform
[transforms.transform_logfmt_logunifier]
type = "remap"
inputs = ["source_journald_logfmt"]
source = '''
 .COM_GITHUB_LOGUNIFIER_APPLICATION_PATTERN_KEY = "logfmt"
'''
## Logfmt logunifer transform END

## Log sources to standdardsaztion channels Begin
[sinks.sink_nats_journald]
type = "nats"
inputs = [ "source_journald","transform_logfmt_logunifier" ]
url = "nats://nats.service.consul:4222"
#url = "nats://10.21.21.42:4222"
# Template syntax is useable here https://vector.dev/docs/reference/configuration/template-syntax/
subject = "ingress.logs.journald"
connection_name ="{{host_name}}-ingress-journald"
encoding.codec ="json"
healthcheck.enabled= true
#buffer.type = "disk"
buffer.when_full="block"
acknowledgements.enabled=true



{% if is_master_host  %}
[sinks.sink_nats_nomad_events]
type = "nats"
inputs = [ "source_nomad_events" ]
url = "nats://nats.service.consul:4222"
#url = "nats://10.21.21.42:4222"
# Template syntax is useable here https://vector.dev/docs/reference/configuration/template-syntax/
subject = "ingress.logs.nomadevents"
connection_name ="{{host_name}}-ingress-nomadevents"
#buffer.type = "disk"
encoding.codec ="json"
healthcheck = true
{% endif %}