#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

timezone= "Etc/UTC"

# Vector's API (disabled by default)
# Enable and try it out with the `vector top` command
[api]
enabled = true
# address = "127.0.0.1:8686"

[sources.source_internal_logs]
type = "internal_logs"

[sources.source_journald]
type = "journald"
current_boot_only = true
exclude_units = ["vector"]
exclude_matches = { }
include_units = [ ]
include_matches = { }


[sources.source_docker_logs]
type = "docker_logs"
# If disabled docker.sock will be used
docker_host = "unix:///var/run/docker.sock"
#include_containers = [ ]
#include_labels = [ ]
#include_images = [ ]
#exclude_containers = []
#tls.ca_file = "/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem"
#tls.crt_file = "/etc/opt/certs/docker/docker-server.pem"
#tls.key_file = "/etc/opt/certs/docker/docker-server-key.pem"



[sinks.sink_stdout]
type = "console"
inputs = ["source_internal_logs","source_journald","source_docker_logs" ]
#inputs = ["source_internal_logs"]
target = "stdout"

[sinks.sink_stdout.encoding]
codec = "json"

[sinks.sink_nats_journald]
type = "nats"
inputs = [ "source_journald" ]
url = "nats://nats.service.consul:4222"
# Template syntax is useable here https://vector.dev/docs/reference/configuration/template-syntax/
subject = "ingress.logs.journald"

[sinks.sink_nats_journald.encoding]
codec = "json"
