# Test {{ '{{' }} env "NOMAD_TASK_NAME"  {{ '}}' }}
# Do not use this configuration in production.
# It is for demonstration purposes only.
# Run Mimir in single process mode, with all components running in 1 process.
target: all,alertmanager,overrides-exporter
multitenancy_enabled: false
#bar: ++  env "NOMAD_TASK_NAME"  ++
blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /data/mimir/tsdb-sync
  filesystem:
    dir: /data/mimir/data/tsdb
  tsdb:
    dir: /data/mimir/tsdb

compactor:
  data_dir: /data/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/mimir/rules

server:
  http_listen_port: 9009
  log_level: debug

store_gateway:
  sharding_ring:
    replication_factor: 1

limits:
  max_label_names_per_series: 42

