- name: Set timezone to UTC
  become: true
  when: not is_devnode
  community.general.timezone:
    name: UTC
  register: ts

- name: "Install timesyncd"
  become: true
  apt:
    name:
      - systemd-timesyncd
    state: present

- name: Set Ntp config
  become: true
  when: not is_devnode
  shell: |
    timedatectl set-ntp true
    systemctl restart systemd-timesyncd
# Add cosutom ntp server in  /etc/systemd/timesyncd.conf
- name: Set Inode settings
  become: true
  changed_when: false
  shell: |
    if [ $(sysctl fs.inotify.max_user_instances | awk '{print $3}') -lt 4096 ]; then sysctl -w fs.inotify.max_user_instances=4096 ;fi
    
- debug:
    msg: "{{ ts }}"
