---
#- name: get service facts
#  service_facts:
#- debug:
#    var: ansible_facts.services['ufw.service']

- name: Nodes setup
  block:

  - name: "Disable firewalld {{host_name}}"
    import_tasks: disable_firewall.yml
  #  when: ansible_facts.services['ufw.service'] is defined and ansible_facts.services['ufw.service']['status'] == 'enabled'

  - name: "Delete users {{host_name}}"
    import_tasks: delete_users.yml

  - name: "Install base packages {{host_name}}"
    import_tasks: install_base_packages.yml


  - name: "Host config {{host_name}}"
    import_tasks: host_config.yml



  - name: "Install oh my zsh {{host_name}}"
    import_tasks: install_ohmy_zsh.yml

  - name: "Config tmux {{host_name}}"
    import_tasks: config_tmux.yml

  - name: "Install cfssl tmux {{host_name}}"
    when: is_master_0
    run_once: true
    import_tasks: install_cfssl.yml

  - name: "copy check config sh to the nodes "
    import_tasks: copy_check_config.yml


  tags:
    - nodes
