- name: "Create user {{create_group}} and group {{create_group}}"
  become: true
  block:
    - name: "Creating group {{ create_group }}"
      group:
        name: "{{ create_group }}"
        state: present

    - name: "Creating user {{ create_user }}"
      user:
        name: "{{ create_user }}"
        group: "{{ create_group }}"
        system: yes
        shell: "/sbin/false"
        comment: "{{ create_user }} nologin User"
        createhome: no
        home: "{{create_usr_conf_dir}}"
        state: present
