== Consul load balancing

Let's assume we deploy the nomad job shown below:

.Nomad whoami service
[source,hcl]
----
job "whoami" {
datacenters = ["nomadder1"]

  group "whoami" {
    count = 6

    network {
      mode = "bridge"
      port "web" {
         to =8080
      }
    }

    service {
      name = "whoami"
      port = "web"

      check {
        name     = "whoami_check"
        type     = "tcp"
        interval = "10s"
        timeout  = "1s"
      }
    }

    task "whoami" {
      driver = "docker"
      config {
        image = "traefik/whoami"
        ports = ["web"]
        args  = ["--port", "${NOMAD_PORT_web}"]
      }

      resources {
        cpu    = 100
        memory = 128
      }
    }
  }
}
----

And now let's dig the service
.Dig whoami
[source,shell]
----
dig whoami.service.consul  SRV

whoami.service.consul.  0       IN      SRV     1 1 30659 0a15152a.addr.nomadder1.consul.
whoami.service.consul.  0       IN      SRV     1 1 23105 0a15152a.addr.nomadder1.consul.
whoami.service.consul.  0       IN      SRV     1 1 26178 0a15152a.addr.nomadder1.consul.
whoami.service.consul.  0       IN      SRV     1 1 27609 0a15152a.addr.nomadder1.consul.
whoami.service.consul.  0       IN      SRV     1 1 30705 0a15152a.addr.nomadder1.consul.
whoami.service.consul.  0       IN      SRV     1 1 29864 0a15152a.addr.nomadder1.consul.

----

Consul is able to register one service multiple times. The dns server changes on every dns request the order of the healthy services. So that the client took everytime the first entry. That mean that is not a service load balancing like traefik does.

=== Consul Teplate
.Consul Template
[source,hcl]
----
# The - suppresses the geretation of new lines
# Query for all consul services . A reference to *dependency.CatalogSnippet
# Name and Tags
{{- range services }}
  #Query the the service. A refrence to *dependency.HealthService
  {{- range service .Name }}
    {{ .Name}} {{.Tags}}
   {{- end}}
{{- end }}
----

.Consul Template with conditions
[source,hcl]
----
{{- range services }}
  {{- range service .Name }}
    {{- if .Tags | contains "prometheus_exporter"}}
      {{ .Name}} : {{.Port}} {{.Tags }}
  {{- end}}
{{- end}}
----


.Consul Template with conditions. Generate if service exists
[source,hcl]
----
Services
{{- $services := service "minio" -}}
{{- if $services -}}
    {{- range $services }}
        {{- range service .Name }}
            {{ .Name}}
        {{- end}}
    {{- end }}
{{- end }}
----


.Consul Template Tags to map
[source,hcl]
----
Services
{{- $services := service "minio" -}}
  {{- if $services -}}
    {{- range $services }}
      {{- range service .Name }}
        {{ .Name}} {{.Tags | join ","| splitToMap "," "="  }}
      {{- end}}
    {{- end }}
{{- end }}
----


.Consul Template select tags value
First capture .Tags. Tags is an array value. Convert the array to a string field delimited by ",". Then convert the array entires delimited by "=" to a map and store it to local value. Access the value over the index value


[source,hcl]
----
Services
{{- $services := service "minio" -}}
  {{- if $services -}}
  {{- range $services -}}
     {{- $labels := .Tags | join ","| splitToMap "," "=" -}}
      {{- if index $labels "traefik.http.routers.minio.rule" -}}
     label={{index $labels "traefik.http.routers.minio.rule"}}
  {{- end }}
{{- end }}
----


.Render template to a file
[source,shell]
----
consul-template -template test.tpl:test.out -once
----
.Render template to stdout
[source,shell]
----
consul-template -template test.tpl -dry
----

==== Consul Template rendering with config

. Crate a cfg file

.Render template config file
[source,hcl]
----
template {
destination = "local/agent.yaml"
right_delimiter = "++"
left_delimiter = "++"
source ="test.tpl"
}
----

. Execute the Template over config

.Render template config file
[source,shell]
----
consul-template  -config test.cfg -dry
----


[[_200_link_consul_agent_client_mode,vault_delete_ca]]https://groups.google.com/g/consul-tool/c/VI1xd8wG-0w[What is purpose and intent of Consul Agents running in Client mode]

[[_200_link_consul_tpl_lang,consul_tpl_lang]]https://github.com/hashicorp/consul-template/blob/main/docs/templating-language.md[Templating Language]



