=== Nomad Reference Architecture
https://developer.hashicorp.com/nomad/tutorials/enterprise/production-reference-architecture-vm-with-consul#ra

=== Nomad Deployment Guide
https://developer.hashicorp.com/nomad/tutorials/enterprise/production-deployment-guide-vm-with-consul

=== Networking
In nomad client config is a `network` stanza.
You can bin there some interfaces to a named physical or virtual betwork on your host.

.Bind two named networks
[source,hcl]
----
 host_network "private" {
   interface = "eth0"
   #cidr = "203.0.113.0/24"
   #reserved_ports = "22,80"
}

host_network "public" {
    interface = "eth1"
}
----

After that you can bind in a job stanza the service to a specific interface

.Bind service to specific interface. For example make http availiable only through private network
[source,hcl]
----
  network {
    port "http-priv" {
      static       = 80
      host_network = "private"
    }
    port "https-priv" {
      static       = 443
      host_network = "private"
    }

    port "https-pub" {
      static       = 443
      host_network = "public"
    }
  }
----


=== Memory and cpu limits
There are two main types of setting resources in nomad. The first in the nomad client configuration and the second is inside in the job configuration.

The resource configuration in the client configuration reserves memory and cpu for operating nomad. after this reservation nomad subtracts this from the available resources for job scheduling.

The resource configuration in the job configuration limits the job itself. If you don't enable https://developer.hashicorp.com/nomad/docs/job-specification/resources#memory-oversubscription[Memory Oversubscription] then the memory you defined is the min and max limit at the same time.

=== Links
[[_200_link_nomad_task_init,nomad task dependencies]]https://developer.hashicorp.com/nomad/tutorials/task-deps/task-dependencies-interjob[Express Inter-job Dependencies with Init Tasks]

[[_200_link_nomad_hcl_lang,nomad hcl lang functions]]https://developer.hashicorp.com/nomad/docs/job-specification/hcl2[Nomad hcl lang functions]

