{
 "title": "BlackBoxChecks",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Availability integrations/blackbox-checks",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "absent_over_time({job=\"integrations/blackbox-checks\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BlackBoxChecks",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (job,instance) (probe_success{job=\"integrations/blackbox-checks\"}==0)",
     "legendFormat": "Failed Probe {{instance}}"
    },
    {
     "expr": " count by (job,instance) (probe_failed_due_to_regex{job=\"integrations/blackbox-checks\"}==1)",
     "legendFormat": "Failed Regex {{instance}}"
    }
   ]
  },
  {
   "title": "Consul Up Metrics",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": " sum_over_time (consul_up{}[1m]) ",
     "legendFormat": "{{instance}} {{job}} {{service}}"
    }
   ]
  },
  {
   "title": "Missing Up Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": " sum_over_time (up{}[1m]) ",
     "legendFormat": "{{instance}} {{job}} {{service}}"
    }
   ]
  }
 ]
}