# See https://learn.hashicorp.com/tutorials/consul/dns-forwarding?in=consul/networking#dnsmasq-setup
- name: DnsMasq
  become: true
  block:

  - name: "Create consul template folder if needed {{consul_template_dir_dnsmasq}}"
    ansible.builtin.file:
      path: "{{consul_template_dir_dnsmasq}}"
      state: directory
      mode: '0755'

  - name: Stop and disable systemd-resolved
    service:
      name: systemd-resolved
      state: stopped
      enabled: false

  - name: Populate service facts
    service_facts:

  - name: "Apt Install dnsmasq"
    when: "'dnsmasq.service' not in services"
    apt:
      update_cache: true
      force_apt_get: true
      name:
        - dnsmasq
      state: present


  - name: Template dnsmasq.conf
    template:
      force: yes
      src: dnsmasq.j2
      dest: "/etc/dnsmasq.d/10-consul"
    register: dnsmasq_conf

  - name: Template consul_template_external_dns.j2
    template:
      force: yes
      src: consul_template_external_dns.j2
      dest: "{{consul_template_file_dnsmasq}}"
    register: dnsmasq_tpl

  - name: "Create /etc/NetworkManager/ if not exists"
    changed_when: false
    ansible.builtin.file:
      path: "/etc/NetworkManager"
      state: directory
      mode: '0755'

  - name: Template NetworkManager.conf
    template:
      force: yes
      src: NetworkManager.j2
      dest: "/etc/NetworkManager/NetworkManager.conf"
    register: nwk_conf

  - name: Start dnsmasq service
    changed_when: false
    service:
      name: dnsmasq
      state: started

  - name: Template consul_template_service.j2
    template:
      force: yes
      src: consul_template_service.j2
      dest: /etc/systemd/system/consulTpl_dnsmasq.service
    register: serviceconfig

  - name: enable consul template dnsmasq service
    service:
      name: consulTpl_dnsmasq
      enabled: yes


  - name: restart consul template service
    changed_when: false
    service:
      name: consulTpl_dnsmasq
      state: restarted

  - name: restart dnsmasq service
    when: dnsmasq_conf.changed or nwk_conf.changed or dnsmasq_conf.changed or dnsmasq_tpl.changed
    changed_when: false
    service:
      name: dnsmasq
      state: restarted

  vars:
    consul_template_dir_dnsmasq : "{{consul_template_base_dir}}/dnsmasq"
    consul_template_file_dnsmasq : "{{consul_template_dir_dnsmasq}}/consul_template_external_dns.tpl"
    consul_cert_path: "{{base_cert_dir}}/consul"
    consul_cert: "{{consul_cert_path}}/consul.pem"
    consul_cert_key: "{{consul_cert_path}}/consul-key.pem"
