# See https://learn.hashicorp.com/tutorials/consul/dns-forwarding?in=consul/networking#dnsmasq-setup
- name: DnsMasq
  become: true
  block:

  - name: Stop and disable systemd-resolved
    service:
      name: systemd-resolved
      state: stopped
      enabled: false

  - name: Template resolv.conf
    template:
      force: yes
      src: resolv.j2
      dest: "/etc/resolv.conf"
    register: resolve_conf
  - name: "Apt Install dnsmasq"
    apt:
      update_cache: true
      force_apt_get: true
      name:
        - dnsmasq
      state: present


  - name: Template dnsmasq.conf
    template:
      force: yes
      src: dnsmasq.j2
      dest: "/etc/dnsmasq.d/10-consul"
    register: dnsmasq_conf

  - name: "Create /etc/NetworkManager/ if not exists"
    changed_when: false
    ansible.builtin.file:
      path: "/etc/NetworkManager"
      state: directory
      mode: '0755'

  - name: Template NetworkManager.conf
    template:
      force: yes
      src: NetworkManager.j2
      dest: "/etc/NetworkManager/NetworkManager.conf"
    register: nwk_conf

  - name: Start dnsmasq service
    changed_when: false
    service:
      name: dnsmasq
      state: started

  - name: restart dnsmasq service
    when: dnsmasq_conf.changed or nwk_conf.changed or dnsmasq_conf.changed
    changed_when: false
    service:
      name: dnsmasq
      state: restarted