# See https://learn.hashicorp.com/tutorials/consul/dns-forwarding?in=consul/networking#dnsmasq-setup
- name: DnsMasq
  become: true
  block:
  - name: Stop and disable systemd-resolved
    service:
      name: systemd-resolved
      state: stopped
      enabled: false


  - name: Template resolv.conf
    template:
      force: yes
      src: resolv.j2
      dest: "/etc/resolv.conf"

  - name: "Install dnsmasq"
    apt:
      name:
        - dnsmasq
      state: present

  - name: Start dnsmasq service
    changed_when: false
    service:
      name: dnsmasq
      state: started



  - name: Template dnsmasq.conf
    template:
      force: yes
      src: dnsmasq.j2
      dest: "/etc/dnsmasq.d/10-consul"

  - name: Template NetworkManager.conf
    template:
      force: yes
      src: NetworkManager.j2
      dest: "/etc/NetworkManager/NetworkManager.conf"


  - name: restart dnsmasq service
    changed_when: false
    service:
      name: dnsmasq
      state: restarted