required_plugins = %w(vagrant-vmware-desktop vagrant-timezone)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

$vm_base_box="suikast42/ubuntu-22.04_64"
$vm_base_box_version="1.3.0"

$vm_mem_master_01 = 8096 # 8 GB RAM for master
$vm_cpus_master_01 = 4
$vm_hostname_master_01 = "master-01"
$vm_master_01_ip = "172.21.1.10"


$vm_mem_worker_01 = 43008  # 42 GB RAM for the workloads
$vm_cpus_worker_01 = 12
$vm_hostname_worker_01 = "worker-01"
$vm_worker_01_ip = "172.21.1.20"

$vm_mem_worker_02 = 14000  # 42 GB RAM for the workloads
$vm_cpus_worker_02 = 4
$vm_hostname_worker_02 = "worker-02"
$vm_worker_02_ip = "172.21.1.21"


$vm_mem_worker_03 = 14000  # 42 GB RAM for the workloads
$vm_cpus_worker_03 = 4
$vm_hostname_worker_03 = "worker-03"
$vm_worker_03_ip = "172.21.1.22"


Vagrant.configure("2") do |config|
  # common settings for server and agent
  config.vm.box = $vm_base_box
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  vagrant_home_path = ENV["VAGRANT_HOME"] ||= "#{ENV["USERPROFILE"]}/.vagrant.d"
  config.ssh.private_key_path = ["#{vagrant_home_path}/insecure_private_key", "../../ssh/id_rsa"]

  # create new user, add it to sudoers and allow ssh login over key
  # TODO Vuru: Somehow the ssh login with winscp not works without a password.
  # Set it with  usermod --password $(echo cloudmaster | openssl passwd -1 -stdin) cloudmaster
  config.vm.provision :shell, privileged: true do |s|
    vm_user = "cloudmaster"
    ssh_pub_key = File.readlines("../../ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
          rm  /home/$USER/.ssh/authorized_keys
          useradd -m -s /bin/bash -U #{vm_user} -p #{vm_user}
          usermod --password $(echo cloudmaster | openssl passwd -1 -stdin) cloudmaster
          mkdir /home/#{vm_user}/.ssh
          echo #{ssh_pub_key} >> /home/#{vm_user}/.ssh/authorized_keys
          chown -R #{vm_user}:#{vm_user} /home/#{vm_user}
          echo "%#{vm_user} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/#{vm_user}
      SHELL
  end

  config.timezone.value = :host
  #master
  config.vm.define "master_01" do |mastercfg|
    mastercfg.vm.provider :vmware_desktop do |master_01|
      mastercfg.vm.hostname = $vm_hostname_master_01
      mastercfg.vm.network :private_network, ip: $vm_master_01_ip, :netmask => "255.255.0.0"
      mastercfg.vm.box_version = $vm_base_box_version
      master_01.gui=true
      master_01.linked_clone = false
      master_01.vmx["memsize"] = $vm_mem_master_01
      master_01.vmx["numvcpus"] = $vm_cpus_master_01
      master_01.vmx['displayname'] =$vm_hostname_master_01
    end
  end

  #worker
  config.vm.define "worker_01" do |workercfg|
    workercfg.vm.provider :vmware_desktop do |worker_01|
      workercfg.vm.hostname = $vm_hostname_worker_01
      workercfg.vm.network :private_network, ip: $vm_worker_01_ip, :netmask => "255.255.0.0"
      workercfg.vm.box_version = $vm_base_box_version
      worker_01.gui=true
      worker_01.linked_clone = false
      worker_01.vmx["memsize"] = $vm_mem_worker_01
      worker_01.vmx["numvcpus"] = $vm_cpus_worker_01
      worker_01.vmx['displayname'] =$vm_hostname_worker_01
    end
  end
  # config.vm.define "worker_02" do |workercfg|
  #   workercfg.vm.provider :vmware_desktop do |worker_02|
  #     workercfg.vm.hostname = $vm_hostname_worker_02
  #     workercfg.vm.network :private_network, ip: $vm_worker_02_ip, :netmask => "255.255.0.0"
  #     workercfg.vm.box_version = $vm_base_box_version
  #     worker_02.gui=true
  #     worker_02.linked_clone = false
  #     worker_02.vmx["memsize"] = $vm_mem_worker_02
  #     worker_02.vmx["numvcpus"] = $vm_cpus_worker_02
  #     worker_02.vmx['displayname'] =$vm_hostname_worker_02
  #   end
  # end
  # config.vm.define "worker_03" do |workercfg|
  #   workercfg.vm.provider :vmware_desktop do |worker_03|
  #     workercfg.vm.hostname = $vm_hostname_worker_03
  #     workercfg.vm.network :private_network, ip: $vm_worker_03_ip, :netmask => "255.255.0.0"
  #     workercfg.vm.box_version = $vm_base_box_version
  #     worker_03.gui=true
  #     worker_03.linked_clone = false
  #     worker_03.vmx["memsize"] = $vm_mem_worker_03
  #     worker_03.vmx["numvcpus"] = $vm_cpus_worker_03
  #     worker_03.vmx['displayname'] =$vm_hostname_worker_03
  #   end
  # end
  # Somehow this part is not working with bento image provisioning
  # Let's do it self
  $disk_resize = <<-SHELL
        echo "Full disk capacity for /dev/sda3"
        # Increase the Physical Volume (pv) to max size
        pvresize /dev/sda3
        # Expand the Logical Volume (LV) to max size to match
        lvresize -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv
        # Expand the filesystem itself
        resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv
  SHELL
  config.vm.provision "shell", inline: $disk_resize, privileged: true

end
