{
 "title": "Nomad jobs",
 "description": "Nomad jobs metrics",
 "tags": [ "nomad-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nomad_client_uptime{datacenter=~\"$datacenter\"}, instance)"
    }
   },
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(nomad_client_uptime, datacenter)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated,namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_total_percent,exported_job)"
    }
   },
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{exported_job=~\"$job\"},task_group)"
    }
   },
   {
    "name": "task",
    "label": "task",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_total_percent{exported_job=~\"$job\", task_group=~\"$group\"},task)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage per job",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(nomad_client_allocs_cpu_total_percent{agent_hostname=~\"$instance\", exported_job=~\"$job\",namespace=~\"$namespace\"}) by(agent_hostname, exported_job,namespace)",
     "legendFormat": "{{exported_job}} "
    }
   ]
  },
  {
   "title": "Memory usage per job",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(nomad_client_allocs_memory_usage{agent_hostname=~\"$instance\", exported_job=~\"$job\",namespace=~\"$namespace\"}) by(agent_hostname, exported_job,namespace)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_percent{agent_hostname=~\"$instance\", exported_job=~\"$job\",namespace=~\"$namespace\", task_group=~\"$group\" ,task=~\"$task\"}) by(agent_hostname, exported_job,namespace,task_group,task)",
     "legendFormat": "{{exported_job}} {{task_group}} {{task}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_usage{agent_hostname=~\"$instance\", exported_job=~\"$job\",namespace=~\"$namespace\", task_group=~\"$group\" ,task=~\"$task\"}) by(agent_hostname, exported_job,namespace,task_group,task)",
     "legendFormat": "{{exported_job}} {{task_group}} {{task}}"
    }
   ]
  },
  {
   "title": "CPU total ticks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_ticks{agent_hostname=~\"$instance\", exported_job=~\"$job\",namespace=~\"$namespace\", task_group=~\"$group\" ,task=~\"$task\"}) by(agent_hostname, exported_job,namespace,task_group,task)",
     "legendFormat": "{{exported_job}} {{task_group}} {{task}}"
    }
   ]
  },
  {
   "title": "Memory cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_cache{agent_hostname=~\"$instance\", exported_job=~\"$job\",namespace=~\"$namespace\", task_group=~\"$group\" ,task=~\"$task\"}) by(agent_hostname, exported_job,namespace,task_group,task)",
     "legendFormat": "{{exported_job}} {{task_group}} {{task}}"
    }
   ]
  },
  {
   "title": "CPU overconsumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg(nomad_client_allocs_cpu_total_ticks{agent_hostname=~\"$instance\", exported_job=~\"$job\",namespace=~\"$namespace\", task_group=~\"$group\" ,task=~\"$task\"}) by(agent_hostname, exported_job,namespace,task_group,task)) / (avg(nomad_client_allocs_cpu_allocated{agent_hostname=~\"$instance\", exported_job=~\"$job\",namespace=~\"$namespace\", task_group=~\"$group\" ,task=~\"$task\"}) by(agent_hostname, exported_job,namespace,task_group,task))",
     "legendFormat": "{{exported_job}} {{task_group}} {{task}}"
    }
   ]
  },
  {
   "title": "Memory overconsumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg(nomad_client_allocs_memory_usage{agent_hostname=~\"$instance\", exported_job=~\"$job\",namespace=~\"$namespace\", task_group=~\"$group\" ,task=~\"$task\"}) by(agent_hostname, exported_job,namespace,task_group,task)) / (avg(nomad_client_allocs_memory_allocated{agent_hostname=~\"$instance\", exported_job=~\"$job\",namespace=~\"$namespace\", task_group=~\"$group\" ,task=~\"$task\"}) by(agent_hostname, exported_job,namespace,task_group,task))",
     "legendFormat": "{{exported_job}} {{task_group}} {{task}}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_rss{job=~\"$job\", instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  }
 ]
}