- name: Create postgres volume
  when: host_name == 'worker-01'
  block:

  - name: Create stack core postgres volumes
    include_tasks: nomad/tasks/nomad_volumes.yml
    loop:
      - { name: 'stack_observability_grafana_volume' , path: '{{stack_observability_grafana_volume}}'}
      - { name: 'stack_observability_mimir_volume' , path: '{{stack_observability_mimir_volume}}'}
      - { name: 'stack_observability_loki_volume' , path: '{{stack_observability_loki_volume}}'}
      - { name: 'stack_observability_tempo_volume' , path: '{{stack_observability_tempo_volume}}'}

  vars:
    stack_observability_grafana_volume: "{{nomad_volumes_dir}}/observability/grafana"
    stack_observability_mimir_volume: "{{nomad_volumes_dir}}/observability/mimir"
    stack_observability_loki_volume: "{{nomad_volumes_dir}}/observability/loki"
    stack_observability_tempo_volume: "{{nomad_volumes_dir}}/observability/tempo"

